// @generated by protoc-gen-es v2.2.3 with parameter "target=ts+js+dts,import_extension=js,import_extension=ts"
// @generated from file users/users.proto (package users, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file users/users.proto.
 */
export declare const file_users_users: GenFile;

/**
 * Message for system or service
 *
 * @generated from message users.Service
 */
export declare type Service = Message<"users.Service"> & {
  /**
   * Unique identifier for the system
   *
   * @generated from field: string service_id = 1;
   */
  serviceId: string;

  /**
   * Name of the system
   *
   * @generated from field: string service_name = 2;
   */
  serviceName: string;
};

/**
 * Describes the message users.Service.
 * Use `create(ServiceSchema)` to create a new message.
 */
export declare const ServiceSchema: GenMessage<Service>;

/**
 * Message for role permissions
 *
 * @generated from message users.Permission
 */
export declare type Permission = Message<"users.Permission"> & {
  /**
   * Unique identifier for the permission
   *
   * @generated from field: string permission_id = 1;
   */
  permissionId: string;

  /**
   * Name of the permission
   *
   * @generated from field: string permission_name = 2;
   */
  permissionName: string;
};

/**
 * Describes the message users.Permission.
 * Use `create(PermissionSchema)` to create a new message.
 */
export declare const PermissionSchema: GenMessage<Permission>;

/**
 * Message for user roles
 *
 * @generated from message users.Role
 */
export declare type Role = Message<"users.Role"> & {
  /**
   * Unique identifier for the user role
   *
   * @generated from field: string role_id = 1;
   */
  roleId: string;

  /**
   * Name of the user role
   *
   * @generated from field: string role_name = 2;
   */
  roleName: string;

  /**
   * List of permissions associated with the role
   *
   * @generated from field: repeated users.Permission permissions = 3;
   */
  permissions: Permission[];
};

/**
 * Describes the message users.Role.
 * Use `create(RoleSchema)` to create a new message.
 */
export declare const RoleSchema: GenMessage<Role>;

/**
 * Message for contracting party or organization
 *
 * @generated from message users.ContractingParty
 */
export declare type ContractingParty = Message<"users.ContractingParty"> & {
  /**
   * Unique identifier for the organization
   *
   * @generated from field: string organization_id = 1;
   */
  organizationId: string;

  /**
   * Name of the organization
   *
   * @generated from field: string organization_name = 2;
   */
  organizationName: string;
};

/**
 * Describes the message users.ContractingParty.
 * Use `create(ContractingPartySchema)` to create a new message.
 */
export declare const ContractingPartySchema: GenMessage<ContractingParty>;

/**
 * Message representing a user profile
 *
 * @generated from message users.UserProfile
 */
export declare type UserProfile = Message<"users.UserProfile"> & {
  /**
   * First and last name of the user
   *
   * @generated from field: string full_name = 1;
   */
  fullName: string;

  /**
   * Email address of the user
   *
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * Phone number of the user
   *
   * @generated from field: string phone_number = 3;
   */
  phoneNumber: string;

  /**
   * Country of the user
   *
   * @generated from field: string country = 4;
   */
  country: string;

  /**
   * Province/state of the user
   *
   * @generated from field: string province = 5;
   */
  province: string;

  /**
   * City where the user resides
   *
   * @generated from field: string city = 6;
   */
  city: string;

  /**
   * First line of the address
   *
   * @generated from field: string address_line_1 = 7;
   */
  addressLine1: string;

  /**
   * Second line of the address (optional)
   *
   * @generated from field: string address_line_2 = 8;
   */
  addressLine2: string;

  /**
   * Zip/postal code
   *
   * @generated from field: string zip_code = 9;
   */
  zipCode: string;
};

/**
 * Describes the message users.UserProfile.
 * Use `create(UserProfileSchema)` to create a new message.
 */
export declare const UserProfileSchema: GenMessage<UserProfile>;

/**
 * Message representing a user
 *
 * @generated from message users.User
 */
export declare type User = Message<"users.User"> & {
  /**
   * Unique identifier for the user
   *
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * The user's profile information
   *
   * @generated from field: users.UserProfile profile = 2;
   */
  profile?: UserProfile;

  /**
   * Roles assigned to the user
   *
   * @generated from field: repeated users.Role roles = 3;
   */
  roles: Role[];

  /**
   * Services the user has access to
   *
   * @generated from field: repeated users.Service services = 4;
   */
  services: Service[];

  /**
   * Current status of the user
   *
   * @generated from field: users.UserStatus status = 5;
   */
  status: UserStatus;

  /**
   * Organization or contracting party
   *
   * @generated from field: users.ContractingParty organization = 6;
   */
  organization?: ContractingParty;

  /**
   * Username (can be email)
   *
   * @generated from field: string username = 7;
   */
  username: string;

  /**
   * Hash of the user's password (sensitive, avoid exposing in responses)
   *
   * @generated from field: string password_hash = 8;
   */
  passwordHash: string;

  /**
   * Timestamp for when user was created
   *
   * @generated from field: google.protobuf.Timestamp created_at = 9;
   */
  createdAt?: Timestamp;

  /**
   * Timestamp for last update
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 10;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message users.User.
 * Use `create(UserSchema)` to create a new message.
 */
export declare const UserSchema: GenMessage<User>;

/**
 * Message for creating a new user request
 *
 * @generated from message users.CreateUserRequest
 */
export declare type CreateUserRequest = Message<"users.CreateUserRequest"> & {
  /**
   * User details to create
   *
   * @generated from field: users.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message users.CreateUserRequest.
 * Use `create(CreateUserRequestSchema)` to create a new message.
 */
export declare const CreateUserRequestSchema: GenMessage<CreateUserRequest>;

/**
 * Message for creating a new user response
 *
 * @generated from message users.CreateUserResponse
 */
export declare type CreateUserResponse = Message<"users.CreateUserResponse"> & {
  /**
   * ID of the created user
   *
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * Confirmation message
   *
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message users.CreateUserResponse.
 * Use `create(CreateUserResponseSchema)` to create a new message.
 */
export declare const CreateUserResponseSchema: GenMessage<CreateUserResponse>;

/**
 * Message for updating user details
 *
 * @generated from message users.UpdateUserRequest
 */
export declare type UpdateUserRequest = Message<"users.UpdateUserRequest"> & {
  /**
   * ID of the user to retrieve
   *
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * Username (can be email)
   *
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * User's password (for authentication)
   *
   * @generated from field: string password = 3;
   */
  password: string;

  /**
   * Updated user 
   *
   * @generated from field: users.User user = 4;
   */
  user?: User;
};

/**
 * Describes the message users.UpdateUserRequest.
 * Use `create(UpdateUserRequestSchema)` to create a new message.
 */
export declare const UpdateUserRequestSchema: GenMessage<UpdateUserRequest>;

/**
 * Message for updating user response
 *
 * @generated from message users.UpdateUserResponse
 */
export declare type UpdateUserResponse = Message<"users.UpdateUserResponse"> & {
  /**
   * Confirmation message
   *
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message users.UpdateUserResponse.
 * Use `create(UpdateUserResponseSchema)` to create a new message.
 */
export declare const UpdateUserResponseSchema: GenMessage<UpdateUserResponse>;

/**
 * Message for retrieving user details by user ID
 *
 * @generated from message users.GetUserRequest
 */
export declare type GetUserRequest = Message<"users.GetUserRequest"> & {
  /**
   * ID of the user to retrieve
   *
   * @generated from field: string user_id = 1;
   */
  userId: string;
};

/**
 * Describes the message users.GetUserRequest.
 * Use `create(GetUserRequestSchema)` to create a new message.
 */
export declare const GetUserRequestSchema: GenMessage<GetUserRequest>;

/**
 * Message for user detail response
 *
 * @generated from message users.GetUserResponse
 */
export declare type GetUserResponse = Message<"users.GetUserResponse"> & {
  /**
   * User information retrieved
   *
   * @generated from field: users.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message users.GetUserResponse.
 * Use `create(GetUserResponseSchema)` to create a new message.
 */
export declare const GetUserResponseSchema: GenMessage<GetUserResponse>;

/**
 * Message for listing users with pagination
 *
 * @generated from message users.ListUsersRequest
 */
export declare type ListUsersRequest = Message<"users.ListUsersRequest"> & {
  /**
   * Number of users per page
   *
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * Token for pagination (optional)
   *
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message users.ListUsersRequest.
 * Use `create(ListUsersRequestSchema)` to create a new message.
 */
export declare const ListUsersRequestSchema: GenMessage<ListUsersRequest>;

/**
 * Message for list users response
 *
 * @generated from message users.ListUsersResponse
 */
export declare type ListUsersResponse = Message<"users.ListUsersResponse"> & {
  /**
   * List of users
   *
   * @generated from field: repeated users.User users = 1;
   */
  users: User[];

  /**
   * Token for the next page (optional)
   *
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;

  /**
   * Total number of users in the system
   *
   * @generated from field: int32 total_count = 3;
   */
  totalCount: number;
};

/**
 * Describes the message users.ListUsersResponse.
 * Use `create(ListUsersResponseSchema)` to create a new message.
 */
export declare const ListUsersResponseSchema: GenMessage<ListUsersResponse>;

/**
 * Message for deleting a user request
 *
 * @generated from message users.DeleteUserRequest
 */
export declare type DeleteUserRequest = Message<"users.DeleteUserRequest"> & {
  /**
   * ID of the user to delete
   *
   * @generated from field: string user_id = 1;
   */
  userId: string;
};

/**
 * Describes the message users.DeleteUserRequest.
 * Use `create(DeleteUserRequestSchema)` to create a new message.
 */
export declare const DeleteUserRequestSchema: GenMessage<DeleteUserRequest>;

/**
 * Message for deleting a user response
 *
 * @generated from message users.DeleteUserResponse
 */
export declare type DeleteUserResponse = Message<"users.DeleteUserResponse"> & {
  /**
   * Confirmation message
   *
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message users.DeleteUserResponse.
 * Use `create(DeleteUserResponseSchema)` to create a new message.
 */
export declare const DeleteUserResponseSchema: GenMessage<DeleteUserResponse>;

/**
 * Enum for user status
 *
 * @generated from enum users.UserStatus
 */
export enum UserStatus {
  /**
   * Default value
   *
   * @generated from enum value: USER_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * User is active and can log in
   *
   * @generated from enum value: USER_STATUS_ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * User has been deactivated
   *
   * @generated from enum value: USER_STATUS_INACTIVE = 2;
   */
  INACTIVE = 2,

  /**
   * User is temporarily suspended
   *
   * @generated from enum value: USER_STATUS_SUSPENDED = 3;
   */
  SUSPENDED = 3,

  /**
   * User account has been deleted
   *
   * @generated from enum value: USER_STATUS_DELETED = 4;
   */
  DELETED = 4,
}

/**
 * Describes the enum users.UserStatus.
 */
export declare const UserStatusSchema: GenEnum<UserStatus>;

/**
 * User Management Service
 *
 * @generated from service users.UsersService
 */
export declare const UsersService: GenService<{
  /**
   * @generated from rpc users.UsersService.GetUser
   */
  getUser: {
    methodKind: "unary";
    input: typeof GetUserRequestSchema;
    output: typeof GetUserResponseSchema;
  },
  /**
   * @generated from rpc users.UsersService.CreateUser
   */
  createUser: {
    methodKind: "unary";
    input: typeof CreateUserRequestSchema;
    output: typeof CreateUserResponseSchema;
  },
  /**
   * @generated from rpc users.UsersService.UpdateUser
   */
  updateUser: {
    methodKind: "unary";
    input: typeof UpdateUserRequestSchema;
    output: typeof UpdateUserResponseSchema;
  },
  /**
   * @generated from rpc users.UsersService.ListUsers
   */
  listUsers: {
    methodKind: "unary";
    input: typeof ListUsersRequestSchema;
    output: typeof ListUsersResponseSchema;
  },
  /**
   * @generated from rpc users.UsersService.DeleteUser
   */
  deleteUser: {
    methodKind: "unary";
    input: typeof DeleteUserRequestSchema;
    output: typeof DeleteUserResponseSchema;
  },
}>;

