// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts+js+dts"
// @generated from file users/users.proto (package users, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateUserRequest, CreateUserResponse, GetUserRequest, GetUserResponse, UpdateUserRequest, UpdateUserResponse, UsersListRequest, UsersListResponse } from "./users_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * User Managment Service
 *
 * @generated from service users.UsersService
 */
export const UsersService = {
  typeName: "users.UsersService",
  methods: {
    /**
     * @generated from rpc users.UsersService.GetUser
     */
    getUser: {
      name: "GetUser",
      I: GetUserRequest,
      O: GetUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc users.UsersService.CreateUser
     */
    createUser: {
      name: "CreateUser",
      I: CreateUserRequest,
      O: CreateUserResponse,
      kind: MethodKind.ClientStreaming,
    },
    /**
     * @generated from rpc users.UsersService.UpdateUser
     */
    updateUser: {
      name: "UpdateUser",
      I: UpdateUserRequest,
      O: UpdateUserResponse,
      kind: MethodKind.ClientStreaming,
    },
    /**
     * @generated from rpc users.UsersService.UsersList
     */
    usersList: {
      name: "UsersList",
      I: UsersListRequest,
      O: UsersListResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
};

