// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: signaling/signaling.proto

package signalingconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	signaling "github.com/az58740/connect-microservices-proto/golang/signaling"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SignalingServiceName is the fully-qualified name of the SignalingService service.
	SignalingServiceName = "signaling.v1.SignalingService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SignalingServiceJoinRoomProcedure is the fully-qualified name of the SignalingService's JoinRoom
	// RPC.
	SignalingServiceJoinRoomProcedure = "/signaling.v1.SignalingService/JoinRoom"
	// SignalingServiceSendSignalProcedure is the fully-qualified name of the SignalingService's
	// SendSignal RPC.
	SignalingServiceSendSignalProcedure = "/signaling.v1.SignalingService/SendSignal"
	// SignalingServiceLeaveRoomProcedure is the fully-qualified name of the SignalingService's
	// LeaveRoom RPC.
	SignalingServiceLeaveRoomProcedure = "/signaling.v1.SignalingService/LeaveRoom"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	signalingServiceServiceDescriptor          = signaling.File_signaling_signaling_proto.Services().ByName("SignalingService")
	signalingServiceJoinRoomMethodDescriptor   = signalingServiceServiceDescriptor.Methods().ByName("JoinRoom")
	signalingServiceSendSignalMethodDescriptor = signalingServiceServiceDescriptor.Methods().ByName("SendSignal")
	signalingServiceLeaveRoomMethodDescriptor  = signalingServiceServiceDescriptor.Methods().ByName("LeaveRoom")
)

// SignalingServiceClient is a client for the signaling.v1.SignalingService service.
type SignalingServiceClient interface {
	JoinRoom(context.Context, *connect.Request[signaling.JoinRoomRequest]) (*connect.ServerStreamForClient[signaling.SignalMessage], error)
	SendSignal(context.Context, *connect.Request[signaling.SignalMessage]) (*connect.Response[signaling.Empty], error)
	LeaveRoom(context.Context, *connect.Request[signaling.LeaveRoomRequest]) (*connect.Response[signaling.Empty], error)
}

// NewSignalingServiceClient constructs a client for the signaling.v1.SignalingService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSignalingServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SignalingServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &signalingServiceClient{
		joinRoom: connect.NewClient[signaling.JoinRoomRequest, signaling.SignalMessage](
			httpClient,
			baseURL+SignalingServiceJoinRoomProcedure,
			connect.WithSchema(signalingServiceJoinRoomMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		sendSignal: connect.NewClient[signaling.SignalMessage, signaling.Empty](
			httpClient,
			baseURL+SignalingServiceSendSignalProcedure,
			connect.WithSchema(signalingServiceSendSignalMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		leaveRoom: connect.NewClient[signaling.LeaveRoomRequest, signaling.Empty](
			httpClient,
			baseURL+SignalingServiceLeaveRoomProcedure,
			connect.WithSchema(signalingServiceLeaveRoomMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// signalingServiceClient implements SignalingServiceClient.
type signalingServiceClient struct {
	joinRoom   *connect.Client[signaling.JoinRoomRequest, signaling.SignalMessage]
	sendSignal *connect.Client[signaling.SignalMessage, signaling.Empty]
	leaveRoom  *connect.Client[signaling.LeaveRoomRequest, signaling.Empty]
}

// JoinRoom calls signaling.v1.SignalingService.JoinRoom.
func (c *signalingServiceClient) JoinRoom(ctx context.Context, req *connect.Request[signaling.JoinRoomRequest]) (*connect.ServerStreamForClient[signaling.SignalMessage], error) {
	return c.joinRoom.CallServerStream(ctx, req)
}

// SendSignal calls signaling.v1.SignalingService.SendSignal.
func (c *signalingServiceClient) SendSignal(ctx context.Context, req *connect.Request[signaling.SignalMessage]) (*connect.Response[signaling.Empty], error) {
	return c.sendSignal.CallUnary(ctx, req)
}

// LeaveRoom calls signaling.v1.SignalingService.LeaveRoom.
func (c *signalingServiceClient) LeaveRoom(ctx context.Context, req *connect.Request[signaling.LeaveRoomRequest]) (*connect.Response[signaling.Empty], error) {
	return c.leaveRoom.CallUnary(ctx, req)
}

// SignalingServiceHandler is an implementation of the signaling.v1.SignalingService service.
type SignalingServiceHandler interface {
	JoinRoom(context.Context, *connect.Request[signaling.JoinRoomRequest], *connect.ServerStream[signaling.SignalMessage]) error
	SendSignal(context.Context, *connect.Request[signaling.SignalMessage]) (*connect.Response[signaling.Empty], error)
	LeaveRoom(context.Context, *connect.Request[signaling.LeaveRoomRequest]) (*connect.Response[signaling.Empty], error)
}

// NewSignalingServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSignalingServiceHandler(svc SignalingServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	signalingServiceJoinRoomHandler := connect.NewServerStreamHandler(
		SignalingServiceJoinRoomProcedure,
		svc.JoinRoom,
		connect.WithSchema(signalingServiceJoinRoomMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	signalingServiceSendSignalHandler := connect.NewUnaryHandler(
		SignalingServiceSendSignalProcedure,
		svc.SendSignal,
		connect.WithSchema(signalingServiceSendSignalMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	signalingServiceLeaveRoomHandler := connect.NewUnaryHandler(
		SignalingServiceLeaveRoomProcedure,
		svc.LeaveRoom,
		connect.WithSchema(signalingServiceLeaveRoomMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/signaling.v1.SignalingService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SignalingServiceJoinRoomProcedure:
			signalingServiceJoinRoomHandler.ServeHTTP(w, r)
		case SignalingServiceSendSignalProcedure:
			signalingServiceSendSignalHandler.ServeHTTP(w, r)
		case SignalingServiceLeaveRoomProcedure:
			signalingServiceLeaveRoomHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSignalingServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSignalingServiceHandler struct{}

func (UnimplementedSignalingServiceHandler) JoinRoom(context.Context, *connect.Request[signaling.JoinRoomRequest], *connect.ServerStream[signaling.SignalMessage]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("signaling.v1.SignalingService.JoinRoom is not implemented"))
}

func (UnimplementedSignalingServiceHandler) SendSignal(context.Context, *connect.Request[signaling.SignalMessage]) (*connect.Response[signaling.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("signaling.v1.SignalingService.SendSignal is not implemented"))
}

func (UnimplementedSignalingServiceHandler) LeaveRoom(context.Context, *connect.Request[signaling.LeaveRoomRequest]) (*connect.Response[signaling.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("signaling.v1.SignalingService.LeaveRoom is not implemented"))
}
