// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: signaling/signaling.proto

package signaling

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Signal Types
type SignalType int32

const (
	SignalType_SIGNAL_TYPE_UNSPECIFIED SignalType = 0
	SignalType_SIGNAL_TYPE_OFFER       SignalType = 1
	SignalType_SIGNAL_TYPE_ANSWER      SignalType = 2
	SignalType_SIGNAL_TYPE_CANDIDATE   SignalType = 3
	SignalType_SIGNAL_TYPE_LEAVE       SignalType = 4
	SignalType_SIGNAL_TYPE_CHAT        SignalType = 5
	SignalType_SIGNAL_USER_JOINED      SignalType = 6
	// انواع برای سناریوی مشاوره
	SignalType_SIGNAL_TYPE_REQUEST_JOIN  SignalType = 7
	SignalType_SIGNAL_TYPE_APPROVE_JOIN  SignalType = 8
	SignalType_SIGNAL_TYPE_REJECT_JOIN   SignalType = 9
	SignalType_SIGNAL_TYPE_OWNER_LEFT    SignalType = 10
	SignalType_SIGNAL_TYPE_ROOM_INFO     SignalType = 11
	SignalType_SIGNAL_TYPE_PENDING_USERS SignalType = 12
	// انواع جدید برای مدیریت روم
	SignalType_SIGNAL_TYPE_ROOM_UPDATED        SignalType = 13
	SignalType_SIGNAL_TYPE_USER_STATUS_CHANGED SignalType = 14
)

// Enum value maps for SignalType.
var (
	SignalType_name = map[int32]string{
		0:  "SIGNAL_TYPE_UNSPECIFIED",
		1:  "SIGNAL_TYPE_OFFER",
		2:  "SIGNAL_TYPE_ANSWER",
		3:  "SIGNAL_TYPE_CANDIDATE",
		4:  "SIGNAL_TYPE_LEAVE",
		5:  "SIGNAL_TYPE_CHAT",
		6:  "SIGNAL_USER_JOINED",
		7:  "SIGNAL_TYPE_REQUEST_JOIN",
		8:  "SIGNAL_TYPE_APPROVE_JOIN",
		9:  "SIGNAL_TYPE_REJECT_JOIN",
		10: "SIGNAL_TYPE_OWNER_LEFT",
		11: "SIGNAL_TYPE_ROOM_INFO",
		12: "SIGNAL_TYPE_PENDING_USERS",
		13: "SIGNAL_TYPE_ROOM_UPDATED",
		14: "SIGNAL_TYPE_USER_STATUS_CHANGED",
	}
	SignalType_value = map[string]int32{
		"SIGNAL_TYPE_UNSPECIFIED":         0,
		"SIGNAL_TYPE_OFFER":               1,
		"SIGNAL_TYPE_ANSWER":              2,
		"SIGNAL_TYPE_CANDIDATE":           3,
		"SIGNAL_TYPE_LEAVE":               4,
		"SIGNAL_TYPE_CHAT":                5,
		"SIGNAL_USER_JOINED":              6,
		"SIGNAL_TYPE_REQUEST_JOIN":        7,
		"SIGNAL_TYPE_APPROVE_JOIN":        8,
		"SIGNAL_TYPE_REJECT_JOIN":         9,
		"SIGNAL_TYPE_OWNER_LEFT":          10,
		"SIGNAL_TYPE_ROOM_INFO":           11,
		"SIGNAL_TYPE_PENDING_USERS":       12,
		"SIGNAL_TYPE_ROOM_UPDATED":        13,
		"SIGNAL_TYPE_USER_STATUS_CHANGED": 14,
	}
)

func (x SignalType) Enum() *SignalType {
	p := new(SignalType)
	*p = x
	return p
}

func (x SignalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalType) Descriptor() protoreflect.EnumDescriptor {
	return file_signaling_signaling_proto_enumTypes[0].Descriptor()
}

func (SignalType) Type() protoreflect.EnumType {
	return &file_signaling_signaling_proto_enumTypes[0]
}

func (x SignalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalType.Descriptor instead.
func (SignalType) EnumDescriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{0}
}

// Room Types
type RoomType int32

const (
	RoomType_ROOM_TYPE_UNSPECIFIED  RoomType = 0
	RoomType_ROOM_TYPE_PEER         RoomType = 1 // همتا به همتا (دکتر و بیمار)
	RoomType_ROOM_TYPE_CONSULTATION RoomType = 2 // یک استاد، چند دانشجو (مشاوره)
	RoomType_ROOM_TYPE_BROADCAST    RoomType = 3 // یک به چند (وبینار، کلاس)
	RoomType_ROOM_TYPE_GROUP        RoomType = 4 // گروهی چند به چند
)

// Enum value maps for RoomType.
var (
	RoomType_name = map[int32]string{
		0: "ROOM_TYPE_UNSPECIFIED",
		1: "ROOM_TYPE_PEER",
		2: "ROOM_TYPE_CONSULTATION",
		3: "ROOM_TYPE_BROADCAST",
		4: "ROOM_TYPE_GROUP",
	}
	RoomType_value = map[string]int32{
		"ROOM_TYPE_UNSPECIFIED":  0,
		"ROOM_TYPE_PEER":         1,
		"ROOM_TYPE_CONSULTATION": 2,
		"ROOM_TYPE_BROADCAST":    3,
		"ROOM_TYPE_GROUP":        4,
	}
)

func (x RoomType) Enum() *RoomType {
	p := new(RoomType)
	*p = x
	return p
}

func (x RoomType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomType) Descriptor() protoreflect.EnumDescriptor {
	return file_signaling_signaling_proto_enumTypes[1].Descriptor()
}

func (RoomType) Type() protoreflect.EnumType {
	return &file_signaling_signaling_proto_enumTypes[1]
}

func (x RoomType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomType.Descriptor instead.
func (RoomType) EnumDescriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{1}
}

// Room Status
type RoomStatus int32

const (
	RoomStatus_ROOM_STATUS_UNSPECIFIED RoomStatus = 0
	RoomStatus_ROOM_STATUS_ACTIVE      RoomStatus = 1 // آنلاین - در حال فعالیت
	RoomStatus_ROOM_STATUS_INACTIVE    RoomStatus = 2 // آفلاین - همه خارج شدند
	RoomStatus_ROOM_STATUS_CLOSED      RoomStatus = 3 // بسته شده توسط صاحب
	RoomStatus_ROOM_STATUS_ARCHIVED    RoomStatus = 4 // آرشیو شده برای گزارش‌گیری
)

// Enum value maps for RoomStatus.
var (
	RoomStatus_name = map[int32]string{
		0: "ROOM_STATUS_UNSPECIFIED",
		1: "ROOM_STATUS_ACTIVE",
		2: "ROOM_STATUS_INACTIVE",
		3: "ROOM_STATUS_CLOSED",
		4: "ROOM_STATUS_ARCHIVED",
	}
	RoomStatus_value = map[string]int32{
		"ROOM_STATUS_UNSPECIFIED": 0,
		"ROOM_STATUS_ACTIVE":      1,
		"ROOM_STATUS_INACTIVE":    2,
		"ROOM_STATUS_CLOSED":      3,
		"ROOM_STATUS_ARCHIVED":    4,
	}
)

func (x RoomStatus) Enum() *RoomStatus {
	p := new(RoomStatus)
	*p = x
	return p
}

func (x RoomStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_signaling_signaling_proto_enumTypes[2].Descriptor()
}

func (RoomStatus) Type() protoreflect.EnumType {
	return &file_signaling_signaling_proto_enumTypes[2]
}

func (x RoomStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomStatus.Descriptor instead.
func (RoomStatus) EnumDescriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{2}
}

// Room Category
type RoomCategory int32

const (
	RoomCategory_ROOM_CATEGORY_UNSPECIFIED      RoomCategory = 0
	RoomCategory_ROOM_CATEGORY_MEDICAL          RoomCategory = 1 // مشاوره پزشکی
	RoomCategory_ROOM_CATEGORY_SKIN_HAIR_BEAUTY RoomCategory = 2 // مشاوره پوست، مو و زیبایی
	RoomCategory_ROOM_CATEGORY_LASER_BEAUTY     RoomCategory = 3 // مشاوره زیبایی و لیزر
	RoomCategory_ROOM_CATEGORY_COSMETIC_BEAUTY  RoomCategory = 4 // مشاوره زیبایی و آرایشی
	RoomCategory_ROOM_CATEGORY_EDUCATIONAL      RoomCategory = 5 // دوره آموزشی و کارگاه
	RoomCategory_ROOM_CATEGORY_OTHER            RoomCategory = 6 // سایر
)

// Enum value maps for RoomCategory.
var (
	RoomCategory_name = map[int32]string{
		0: "ROOM_CATEGORY_UNSPECIFIED",
		1: "ROOM_CATEGORY_MEDICAL",
		2: "ROOM_CATEGORY_SKIN_HAIR_BEAUTY",
		3: "ROOM_CATEGORY_LASER_BEAUTY",
		4: "ROOM_CATEGORY_COSMETIC_BEAUTY",
		5: "ROOM_CATEGORY_EDUCATIONAL",
		6: "ROOM_CATEGORY_OTHER",
	}
	RoomCategory_value = map[string]int32{
		"ROOM_CATEGORY_UNSPECIFIED":      0,
		"ROOM_CATEGORY_MEDICAL":          1,
		"ROOM_CATEGORY_SKIN_HAIR_BEAUTY": 2,
		"ROOM_CATEGORY_LASER_BEAUTY":     3,
		"ROOM_CATEGORY_COSMETIC_BEAUTY":  4,
		"ROOM_CATEGORY_EDUCATIONAL":      5,
		"ROOM_CATEGORY_OTHER":            6,
	}
)

func (x RoomCategory) Enum() *RoomCategory {
	p := new(RoomCategory)
	*p = x
	return p
}

func (x RoomCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_signaling_signaling_proto_enumTypes[3].Descriptor()
}

func (RoomCategory) Type() protoreflect.EnumType {
	return &file_signaling_signaling_proto_enumTypes[3]
}

func (x RoomCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomCategory.Descriptor instead.
func (RoomCategory) EnumDescriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{3}
}

// User Role
type UserRole int32

const (
	UserRole_USER_ROLE_UNSPECIFIED UserRole = 0
	UserRole_USER_ROLE_OWNER       UserRole = 1 // صاحب روم (دکتر، استاد، مشاور)
	UserRole_USER_ROLE_PARTICIPANT UserRole = 2 // شرکت‌کننده تایید شده
	UserRole_USER_ROLE_PENDING     UserRole = 3 // در انتظار تایید
	UserRole_USER_ROLE_MODERATOR   UserRole = 4 // مدیر جلسه (برای کلاس‌های بزرگ)
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "USER_ROLE_UNSPECIFIED",
		1: "USER_ROLE_OWNER",
		2: "USER_ROLE_PARTICIPANT",
		3: "USER_ROLE_PENDING",
		4: "USER_ROLE_MODERATOR",
	}
	UserRole_value = map[string]int32{
		"USER_ROLE_UNSPECIFIED": 0,
		"USER_ROLE_OWNER":       1,
		"USER_ROLE_PARTICIPANT": 2,
		"USER_ROLE_PENDING":     3,
		"USER_ROLE_MODERATOR":   4,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_signaling_signaling_proto_enumTypes[4].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_signaling_signaling_proto_enumTypes[4]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{4}
}

// User Status
type UserStatus int32

const (
	UserStatus_USER_STATUS_UNSPECIFIED UserStatus = 0
	UserStatus_USER_STATUS_ONLINE      UserStatus = 1 // آنلاین
	UserStatus_USER_STATUS_OFFLINE     UserStatus = 2 // آفلاین
	UserStatus_USER_STATUS_AWAY        UserStatus = 3 // موقتاً خارج
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "USER_STATUS_UNSPECIFIED",
		1: "USER_STATUS_ONLINE",
		2: "USER_STATUS_OFFLINE",
		3: "USER_STATUS_AWAY",
	}
	UserStatus_value = map[string]int32{
		"USER_STATUS_UNSPECIFIED": 0,
		"USER_STATUS_ONLINE":      1,
		"USER_STATUS_OFFLINE":     2,
		"USER_STATUS_AWAY":        3,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_signaling_signaling_proto_enumTypes[5].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_signaling_signaling_proto_enumTypes[5]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{5}
}

// Client
type Client struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName        string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	RoomId          string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserPhonenumber string                 `protobuf:"bytes,4,opt,name=user_phonenumber,json=userPhonenumber,proto3" json:"user_phonenumber,omitempty"` // User's phone number.
	Role            UserRole               `protobuf:"varint,5,opt,name=role,proto3,enum=signaling.v1.UserRole" json:"role,omitempty"`
	Status          UserStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=signaling.v1.UserStatus" json:"status,omitempty"`
	JoinedAt        string                 `protobuf:"bytes,7,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	LastSeenAt      string                 `protobuf:"bytes,8,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Duration        int32                  `protobuf:"varint,10,opt,name=duration,proto3" json:"duration,omitempty"`                         // مدت حضور (ثانیه) - فقط برای اعضای روم
	IsMuted         bool                   `protobuf:"varint,11,opt,name=is_muted,json=isMuted,proto3" json:"is_muted,omitempty"`            // میکروفن خاموش؟ - فقط برای اعضای روم
	IsVideoOff      bool                   `protobuf:"varint,12,opt,name=is_video_off,json=isVideoOff,proto3" json:"is_video_off,omitempty"` // ویدیو خاموش؟ - فقط برای اعضای روم
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_signaling_signaling_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{0}
}

func (x *Client) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Client) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Client) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Client) GetUserPhonenumber() string {
	if x != nil {
		return x.UserPhonenumber
	}
	return ""
}

func (x *Client) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_USER_ROLE_UNSPECIFIED
}

func (x *Client) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

func (x *Client) GetJoinedAt() string {
	if x != nil {
		return x.JoinedAt
	}
	return ""
}

func (x *Client) GetLastSeenAt() string {
	if x != nil {
		return x.LastSeenAt
	}
	return ""
}

func (x *Client) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Client) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Client) GetIsMuted() bool {
	if x != nil {
		return x.IsMuted
	}
	return false
}

func (x *Client) GetIsVideoOff() bool {
	if x != nil {
		return x.IsVideoOff
	}
	return false
}

type ClientFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // برای دریافت   یک روم خاص
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // برای دریافت کلاینت های یک روم خاص
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`              // فیلتر بر اساس وضعیت
	Phonenumber   string                 `protobuf:"bytes,4,opt,name=phonenumber,proto3" json:"phonenumber,omitempty"`
	Role          int32                  `protobuf:"varint,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFilter) Reset() {
	*x = ClientFilter{}
	mi := &file_signaling_signaling_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFilter) ProtoMessage() {}

func (x *ClientFilter) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFilter.ProtoReflect.Descriptor instead.
func (*ClientFilter) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{1}
}

func (x *ClientFilter) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ClientFilter) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ClientFilter) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ClientFilter) GetPhonenumber() string {
	if x != nil {
		return x.Phonenumber
	}
	return ""
}

func (x *ClientFilter) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

// Room
type Room struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// اطلاعات پایه
	RoomId      string       `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Name        string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`               // عنوان کامل با جزئیات
	Description string       `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // توضیحات
	RoomType    RoomType     `protobuf:"varint,4,opt,name=room_type,json=roomType,proto3,enum=signaling.v1.RoomType" json:"room_type,omitempty"`
	Category    RoomCategory `protobuf:"varint,5,opt,name=category,proto3,enum=signaling.v1.RoomCategory" json:"category,omitempty"` // دسته‌بندی کلی
	Status      RoomStatus   `protobuf:"varint,6,opt,name=status,proto3,enum=signaling.v1.RoomStatus" json:"status,omitempty"`
	// اطلاعات صاحب
	OwnerId   string `protobuf:"bytes,7,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OwnerName string `protobuf:"bytes,8,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	// کاربران
	Clients        []*Client `protobuf:"bytes,9,rep,name=clients,proto3" json:"clients,omitempty"`                                      // کاربران حاضر (تایید شده)
	PendingClients []*Client `protobuf:"bytes,10,rep,name=pending_clients,json=pendingClients,proto3" json:"pending_clients,omitempty"` // کاربران در انتظار تایید
	OnlineCount    int32     `protobuf:"varint,11,opt,name=online_count,json=onlineCount,proto3" json:"online_count,omitempty"`
	// تنظیمات
	MaxParticipants int32 `protobuf:"varint,12,opt,name=max_participants,json=maxParticipants,proto3" json:"max_participants,omitempty"`
	IsPrivate       bool  `protobuf:"varint,13,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	HasPassword     bool  `protobuf:"varint,14,opt,name=has_password,json=hasPassword,proto3" json:"has_password,omitempty"`
	// زمان‌ها
	CreatedAt    string `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt    string `protobuf:"bytes,16,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`            // زمان شروع جلسه
	LastActiveAt string `protobuf:"bytes,17,opt,name=last_active_at,json=lastActiveAt,proto3" json:"last_active_at,omitempty"` // آخرین فعالیت
	// آمار
	TotalParticipants int32 `protobuf:"varint,18,opt,name=total_participants,json=totalParticipants,proto3" json:"total_participants,omitempty"` // کل شرکت‌کنندگان
	PeakParticipants  int32 `protobuf:"varint,19,opt,name=peak_participants,json=peakParticipants,proto3" json:"peak_participants,omitempty"`    // بیشترین تعداد همزمان
	// اطلاعات اضافی
	PricePerMinute float32           `protobuf:"fixed32,20,opt,name=price_per_minute,json=pricePerMinute,proto3" json:"price_per_minute,omitempty"`
	Tags           []string          `protobuf:"bytes,21,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata       map[string]string `protobuf:"bytes,22,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Settings       map[string]string `protobuf:"bytes,23,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ThumbnailUrl   string            `protobuf:"bytes,24,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"` // تصویر (اختیاری)
	Rating         float32           `protobuf:"fixed32,25,opt,name=rating,proto3" json:"rating,omitempty"`                               // امتیاز (برای روم‌های مشاوره)
	ReviewCount    int32             `protobuf:"varint,26,opt,name=review_count,json=reviewCount,proto3" json:"review_count,omitempty"`   // تعداد نظرات
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_signaling_signaling_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{2}
}

func (x *Room) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Room) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Room) GetRoomType() RoomType {
	if x != nil {
		return x.RoomType
	}
	return RoomType_ROOM_TYPE_UNSPECIFIED
}

func (x *Room) GetCategory() RoomCategory {
	if x != nil {
		return x.Category
	}
	return RoomCategory_ROOM_CATEGORY_UNSPECIFIED
}

func (x *Room) GetStatus() RoomStatus {
	if x != nil {
		return x.Status
	}
	return RoomStatus_ROOM_STATUS_UNSPECIFIED
}

func (x *Room) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Room) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *Room) GetClients() []*Client {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *Room) GetPendingClients() []*Client {
	if x != nil {
		return x.PendingClients
	}
	return nil
}

func (x *Room) GetOnlineCount() int32 {
	if x != nil {
		return x.OnlineCount
	}
	return 0
}

func (x *Room) GetMaxParticipants() int32 {
	if x != nil {
		return x.MaxParticipants
	}
	return 0
}

func (x *Room) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *Room) GetHasPassword() bool {
	if x != nil {
		return x.HasPassword
	}
	return false
}

func (x *Room) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Room) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *Room) GetLastActiveAt() string {
	if x != nil {
		return x.LastActiveAt
	}
	return ""
}

func (x *Room) GetTotalParticipants() int32 {
	if x != nil {
		return x.TotalParticipants
	}
	return 0
}

func (x *Room) GetPeakParticipants() int32 {
	if x != nil {
		return x.PeakParticipants
	}
	return 0
}

func (x *Room) GetPricePerMinute() float32 {
	if x != nil {
		return x.PricePerMinute
	}
	return 0
}

func (x *Room) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Room) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Room) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Room) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *Room) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Room) GetReviewCount() int32 {
	if x != nil {
		return x.ReviewCount
	}
	return 0
}

// SignalMessage (برای stream)
type SignalMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	FromUser      string                 `protobuf:"bytes,2,opt,name=from_user,json=fromUser,proto3" json:"from_user,omitempty"`
	FromUserName  string                 `protobuf:"bytes,3,opt,name=from_user_name,json=fromUserName,proto3" json:"from_user_name,omitempty"`
	ToUser        string                 `protobuf:"bytes,4,opt,name=to_user,json=toUser,proto3" json:"to_user,omitempty"`
	ToUserName    string                 `protobuf:"bytes,5,opt,name=to_user_name,json=toUserName,proto3" json:"to_user_name,omitempty"`
	Type          SignalType             `protobuf:"varint,6,opt,name=type,proto3,enum=signaling.v1.SignalType" json:"type,omitempty"`
	Payload       string                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	Message       string                 `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalMessage) Reset() {
	*x = SignalMessage{}
	mi := &file_signaling_signaling_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalMessage) ProtoMessage() {}

func (x *SignalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalMessage.ProtoReflect.Descriptor instead.
func (*SignalMessage) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{3}
}

func (x *SignalMessage) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SignalMessage) GetFromUser() string {
	if x != nil {
		return x.FromUser
	}
	return ""
}

func (x *SignalMessage) GetFromUserName() string {
	if x != nil {
		return x.FromUserName
	}
	return ""
}

func (x *SignalMessage) GetToUser() string {
	if x != nil {
		return x.ToUser
	}
	return ""
}

func (x *SignalMessage) GetToUserName() string {
	if x != nil {
		return x.ToUserName
	}
	return ""
}

func (x *SignalMessage) GetType() SignalType {
	if x != nil {
		return x.Type
	}
	return SignalType_SIGNAL_TYPE_UNSPECIFIED
}

func (x *SignalMessage) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *SignalMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SignalMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// JoinRoom
type JoinRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	IsOwner       bool                   `protobuf:"varint,4,opt,name=is_owner,json=isOwner,proto3" json:"is_owner,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	mi := &file_signaling_signaling_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{4}
}

func (x *JoinRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinRoomRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinRoomRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *JoinRoomRequest) GetIsOwner() bool {
	if x != nil {
		return x.IsOwner
	}
	return false
}

func (x *JoinRoomRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type JoinRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomResponse) Reset() {
	*x = JoinRoomResponse{}
	mi := &file_signaling_signaling_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResponse) ProtoMessage() {}

func (x *JoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResponse.ProtoReflect.Descriptor instead.
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{5}
}

func (x *JoinRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// SendSignal
type SendSignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signal        *SignalMessage         `protobuf:"bytes,1,opt,name=signal,proto3" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSignalRequest) Reset() {
	*x = SendSignalRequest{}
	mi := &file_signaling_signaling_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSignalRequest) ProtoMessage() {}

func (x *SendSignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSignalRequest.ProtoReflect.Descriptor instead.
func (*SendSignalRequest) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{6}
}

func (x *SendSignalRequest) GetSignal() *SignalMessage {
	if x != nil {
		return x.Signal
	}
	return nil
}

type SendSignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivered     bool                   `protobuf:"varint,1,opt,name=delivered,proto3" json:"delivered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSignalResponse) Reset() {
	*x = SendSignalResponse{}
	mi := &file_signaling_signaling_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSignalResponse) ProtoMessage() {}

func (x *SendSignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSignalResponse.ProtoReflect.Descriptor instead.
func (*SendSignalResponse) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{7}
}

func (x *SendSignalResponse) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

// LeaveRoom
type LeaveRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomRequest) Reset() {
	*x = LeaveRoomRequest{}
	mi := &file_signaling_signaling_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomRequest) ProtoMessage() {}

func (x *LeaveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomRequest.ProtoReflect.Descriptor instead.
func (*LeaveRoomRequest) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{8}
}

func (x *LeaveRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *LeaveRoomRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LeaveRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomResponse) Reset() {
	*x = LeaveRoomResponse{}
	mi := &file_signaling_signaling_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomResponse) ProtoMessage() {}

func (x *LeaveRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomResponse.ProtoReflect.Descriptor instead.
func (*LeaveRoomResponse) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{9}
}

func (x *LeaveRoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetRooms
type RoomFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// فیلتر بر اساس شناسه (برای دریافت یک روم خاص)
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// فیلتر بر اساس وضعیت
	Status     RoomStatus `protobuf:"varint,2,opt,name=status,proto3,enum=signaling.v1.RoomStatus" json:"status,omitempty"`
	OnlyOnline bool       `protobuf:"varint,3,opt,name=only_online,json=onlyOnline,proto3" json:"only_online,omitempty"` // فقط روم‌های آنلاین
	// فیلتر بر اساس دسته‌بندی کلی
	Category RoomCategory `protobuf:"varint,4,opt,name=category,proto3,enum=signaling.v1.RoomCategory" json:"category,omitempty"`
	// فیلتر بر اساس نوع روم
	RoomType RoomType `protobuf:"varint,5,opt,name=room_type,json=roomType,proto3,enum=signaling.v1.RoomType" json:"room_type,omitempty"`
	// فیلتر بر اساس صاحب روم
	OwnerId string `protobuf:"bytes,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// فیلتر بر اساس کاربر عضو
	MemberUserId string `protobuf:"bytes,7,opt,name=member_user_id,json=memberUserId,proto3" json:"member_user_id,omitempty"` // روم‌هایی که کاربر خاصی عضو است
	// جستجو در متن (name و description)
	SearchQuery string `protobuf:"bytes,8,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	// محدوده قیمت
	MinPrice float32 `protobuf:"fixed32,9,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice float32 `protobuf:"fixed32,10,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	// برچسب‌ها
	Tags          []string `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomFilter) Reset() {
	*x = RoomFilter{}
	mi := &file_signaling_signaling_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomFilter) ProtoMessage() {}

func (x *RoomFilter) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomFilter.ProtoReflect.Descriptor instead.
func (*RoomFilter) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{10}
}

func (x *RoomFilter) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomFilter) GetStatus() RoomStatus {
	if x != nil {
		return x.Status
	}
	return RoomStatus_ROOM_STATUS_UNSPECIFIED
}

func (x *RoomFilter) GetOnlyOnline() bool {
	if x != nil {
		return x.OnlyOnline
	}
	return false
}

func (x *RoomFilter) GetCategory() RoomCategory {
	if x != nil {
		return x.Category
	}
	return RoomCategory_ROOM_CATEGORY_UNSPECIFIED
}

func (x *RoomFilter) GetRoomType() RoomType {
	if x != nil {
		return x.RoomType
	}
	return RoomType_ROOM_TYPE_UNSPECIFIED
}

func (x *RoomFilter) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *RoomFilter) GetMemberUserId() string {
	if x != nil {
		return x.MemberUserId
	}
	return ""
}

func (x *RoomFilter) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

func (x *RoomFilter) GetMinPrice() float32 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *RoomFilter) GetMaxPrice() float32 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *RoomFilter) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type GetRoomsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// فیلتر بر اساس شناسه (برای دریافت یک روم خاص)
	RoomId string `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// فیلتر بر اساس وضعیت
	Status     RoomStatus `protobuf:"varint,2,opt,name=status,proto3,enum=signaling.v1.RoomStatus" json:"status,omitempty"`
	OnlyOnline bool       `protobuf:"varint,3,opt,name=only_online,json=onlyOnline,proto3" json:"only_online,omitempty"` // فقط روم‌های آنلاین
	// فیلتر بر اساس دسته‌بندی کلی
	Category RoomCategory `protobuf:"varint,4,opt,name=category,proto3,enum=signaling.v1.RoomCategory" json:"category,omitempty"`
	// فیلتر بر اساس نوع روم
	RoomType RoomType `protobuf:"varint,5,opt,name=room_type,json=roomType,proto3,enum=signaling.v1.RoomType" json:"room_type,omitempty"`
	// فیلتر بر اساس صاحب روم
	OwnerId string `protobuf:"bytes,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// فیلتر بر اساس کاربر عضو
	MemberUserId string `protobuf:"bytes,7,opt,name=member_user_id,json=memberUserId,proto3" json:"member_user_id,omitempty"` // روم‌هایی که کاربر خاصی عضو است
	// جستجو در متن (name و description)
	SearchQuery string `protobuf:"bytes,8,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	// محدوده قیمت
	MinPrice float32 `protobuf:"fixed32,9,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice float32 `protobuf:"fixed32,10,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	// برچسب‌ها
	Tags          []string `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"` // روم‌هایی که این برچسب‌ها را دارند
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomsRequest) Reset() {
	*x = GetRoomsRequest{}
	mi := &file_signaling_signaling_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomsRequest) ProtoMessage() {}

func (x *GetRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomsRequest.ProtoReflect.Descriptor instead.
func (*GetRoomsRequest) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{11}
}

func (x *GetRoomsRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetRoomsRequest) GetStatus() RoomStatus {
	if x != nil {
		return x.Status
	}
	return RoomStatus_ROOM_STATUS_UNSPECIFIED
}

func (x *GetRoomsRequest) GetOnlyOnline() bool {
	if x != nil {
		return x.OnlyOnline
	}
	return false
}

func (x *GetRoomsRequest) GetCategory() RoomCategory {
	if x != nil {
		return x.Category
	}
	return RoomCategory_ROOM_CATEGORY_UNSPECIFIED
}

func (x *GetRoomsRequest) GetRoomType() RoomType {
	if x != nil {
		return x.RoomType
	}
	return RoomType_ROOM_TYPE_UNSPECIFIED
}

func (x *GetRoomsRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *GetRoomsRequest) GetMemberUserId() string {
	if x != nil {
		return x.MemberUserId
	}
	return ""
}

func (x *GetRoomsRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

func (x *GetRoomsRequest) GetMinPrice() float32 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *GetRoomsRequest) GetMaxPrice() float32 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *GetRoomsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type GetRoomsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// اگر room_id در درخواست مشخص شده بود
	Room *Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	// اگر درخواست لیست بود
	Rooms []*Room `protobuf:"bytes,2,rep,name=rooms,proto3" json:"rooms,omitempty"`
	// تعداد کل نتایج
	TotalCount    int32 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomsResponse) Reset() {
	*x = GetRoomsResponse{}
	mi := &file_signaling_signaling_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomsResponse) ProtoMessage() {}

func (x *GetRoomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomsResponse.ProtoReflect.Descriptor instead.
func (*GetRoomsResponse) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{12}
}

func (x *GetRoomsResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *GetRoomsResponse) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *GetRoomsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// CreateRoom
type CreateRoomRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoomId          string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` // اگر خالی بود، سرور تولید می‌کند
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	RoomType        RoomType               `protobuf:"varint,4,opt,name=room_type,json=roomType,proto3,enum=signaling.v1.RoomType" json:"room_type,omitempty"`
	Category        RoomCategory           `protobuf:"varint,5,opt,name=category,proto3,enum=signaling.v1.RoomCategory" json:"category,omitempty"`
	MaxParticipants int32                  `protobuf:"varint,6,opt,name=max_participants,json=maxParticipants,proto3" json:"max_participants,omitempty"`
	IsPrivate       bool                   `protobuf:"varint,7,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	Password        string                 `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	Settings        map[string]string      `protobuf:"bytes,9,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PricePerMinute  float32                `protobuf:"fixed32,10,opt,name=price_per_minute,json=pricePerMinute,proto3" json:"price_per_minute,omitempty"`
	Tags            []string               `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	OwnerId         string                 `protobuf:"bytes,12,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Status          RoomStatus             `protobuf:"varint,13,opt,name=status,proto3,enum=signaling.v1.RoomStatus" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_signaling_signaling_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{13}
}

func (x *CreateRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateRoomRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoomRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRoomRequest) GetRoomType() RoomType {
	if x != nil {
		return x.RoomType
	}
	return RoomType_ROOM_TYPE_UNSPECIFIED
}

func (x *CreateRoomRequest) GetCategory() RoomCategory {
	if x != nil {
		return x.Category
	}
	return RoomCategory_ROOM_CATEGORY_UNSPECIFIED
}

func (x *CreateRoomRequest) GetMaxParticipants() int32 {
	if x != nil {
		return x.MaxParticipants
	}
	return 0
}

func (x *CreateRoomRequest) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *CreateRoomRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateRoomRequest) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *CreateRoomRequest) GetPricePerMinute() float32 {
	if x != nil {
		return x.PricePerMinute
	}
	return 0
}

func (x *CreateRoomRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateRoomRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateRoomRequest) GetStatus() RoomStatus {
	if x != nil {
		return x.Status
	}
	return RoomStatus_ROOM_STATUS_UNSPECIFIED
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_signaling_signaling_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{14}
}

func (x *CreateRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// UpdateRoomSettings
type UpdateRoomSettingsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoomId          string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // برای اعتبارسنجی (فقط owner می‌تواند)
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Category        RoomCategory           `protobuf:"varint,5,opt,name=category,proto3,enum=signaling.v1.RoomCategory" json:"category,omitempty"`
	MaxParticipants int32                  `protobuf:"varint,6,opt,name=max_participants,json=maxParticipants,proto3" json:"max_participants,omitempty"`
	IsPrivate       bool                   `protobuf:"varint,7,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`
	Password        string                 `protobuf:"bytes,8,opt,name=password,proto3" json:"password,omitempty"`
	Settings        map[string]string      `protobuf:"bytes,9,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PricePerMinute  float32                `protobuf:"fixed32,10,opt,name=price_per_minute,json=pricePerMinute,proto3" json:"price_per_minute,omitempty"`
	Tags            []string               `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateRoomSettingsRequest) Reset() {
	*x = UpdateRoomSettingsRequest{}
	mi := &file_signaling_signaling_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomSettingsRequest) ProtoMessage() {}

func (x *UpdateRoomSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoomSettingsRequest) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateRoomSettingsRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UpdateRoomSettingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateRoomSettingsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRoomSettingsRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateRoomSettingsRequest) GetCategory() RoomCategory {
	if x != nil {
		return x.Category
	}
	return RoomCategory_ROOM_CATEGORY_UNSPECIFIED
}

func (x *UpdateRoomSettingsRequest) GetMaxParticipants() int32 {
	if x != nil {
		return x.MaxParticipants
	}
	return 0
}

func (x *UpdateRoomSettingsRequest) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *UpdateRoomSettingsRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateRoomSettingsRequest) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *UpdateRoomSettingsRequest) GetPricePerMinute() float32 {
	if x != nil {
		return x.PricePerMinute
	}
	return 0
}

func (x *UpdateRoomSettingsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type UpdateRoomSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomSettingsResponse) Reset() {
	*x = UpdateRoomSettingsResponse{}
	mi := &file_signaling_signaling_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomSettingsResponse) ProtoMessage() {}

func (x *UpdateRoomSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoomSettingsResponse) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateRoomSettingsResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// CloseRoom
type CloseRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // برای اعتبارسنجی (فقط owner می‌تواند)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRoomRequest) Reset() {
	*x = CloseRoomRequest{}
	mi := &file_signaling_signaling_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRoomRequest) ProtoMessage() {}

func (x *CloseRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRoomRequest.ProtoReflect.Descriptor instead.
func (*CloseRoomRequest) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{17}
}

func (x *CloseRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CloseRoomRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CloseRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRoomResponse) Reset() {
	*x = CloseRoomResponse{}
	mi := &file_signaling_signaling_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRoomResponse) ProtoMessage() {}

func (x *CloseRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRoomResponse.ProtoReflect.Descriptor instead.
func (*CloseRoomResponse) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{18}
}

func (x *CloseRoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CloseRoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// RemoveRoom
type RemoveRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // برای اعتبارسنجی (فقط owner می‌تواند)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRoomRequest) Reset() {
	*x = RemoveRoomRequest{}
	mi := &file_signaling_signaling_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRoomRequest) ProtoMessage() {}

func (x *RemoveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRoomRequest.ProtoReflect.Descriptor instead.
func (*RemoveRoomRequest) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{19}
}

func (x *RemoveRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RemoveRoomRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRoomResponse) Reset() {
	*x = RemoveRoomResponse{}
	mi := &file_signaling_signaling_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRoomResponse) ProtoMessage() {}

func (x *RemoveRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRoomResponse.ProtoReflect.Descriptor instead.
func (*RemoveRoomResponse) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{20}
}

func (x *RemoveRoomResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveRoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

//CreateClient
type CreateClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Phonenumber   string                 `protobuf:"bytes,4,opt,name=phonenumber,proto3" json:"phonenumber,omitempty"`
	Role          UserRole               `protobuf:"varint,5,opt,name=role,proto3,enum=signaling.v1.UserRole" json:"role,omitempty"`
	Status        UserStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=signaling.v1.UserStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientRequest) Reset() {
	*x = CreateClientRequest{}
	mi := &file_signaling_signaling_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientRequest) ProtoMessage() {}

func (x *CreateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientRequest.ProtoReflect.Descriptor instead.
func (*CreateClientRequest) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{21}
}

func (x *CreateClientRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateClientRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateClientRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateClientRequest) GetPhonenumber() string {
	if x != nil {
		return x.Phonenumber
	}
	return ""
}

func (x *CreateClientRequest) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_USER_ROLE_UNSPECIFIED
}

func (x *CreateClientRequest) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

type CreateClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        *Client                `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientResponse) Reset() {
	*x = CreateClientResponse{}
	mi := &file_signaling_signaling_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientResponse) ProtoMessage() {}

func (x *CreateClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientResponse.ProtoReflect.Descriptor instead.
func (*CreateClientResponse) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{22}
}

func (x *CreateClientResponse) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

// GetRoomClients
type GetRoomClientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *ClientFilter          `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomClientsRequest) Reset() {
	*x = GetRoomClientsRequest{}
	mi := &file_signaling_signaling_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomClientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomClientsRequest) ProtoMessage() {}

func (x *GetRoomClientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomClientsRequest.ProtoReflect.Descriptor instead.
func (*GetRoomClientsRequest) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{23}
}

func (x *GetRoomClientsRequest) GetFilter() *ClientFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type GetRoomClientsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Clients        []*Client              `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`                                     // کاربران حاضر (تایید شده)
	PendingClients []*Client              `protobuf:"bytes,2,rep,name=pending_clients,json=pendingClients,proto3" json:"pending_clients,omitempty"` // کاربران در انتظار تایید
	TotalCount     int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	OnlineCount    int32                  `protobuf:"varint,4,opt,name=online_count,json=onlineCount,proto3" json:"online_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRoomClientsResponse) Reset() {
	*x = GetRoomClientsResponse{}
	mi := &file_signaling_signaling_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomClientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomClientsResponse) ProtoMessage() {}

func (x *GetRoomClientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomClientsResponse.ProtoReflect.Descriptor instead.
func (*GetRoomClientsResponse) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{24}
}

func (x *GetRoomClientsResponse) GetClients() []*Client {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *GetRoomClientsResponse) GetPendingClients() []*Client {
	if x != nil {
		return x.PendingClients
	}
	return nil
}

func (x *GetRoomClientsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetRoomClientsResponse) GetOnlineCount() int32 {
	if x != nil {
		return x.OnlineCount
	}
	return 0
}

// UpdateClientStatus
type UpdateClientStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        UserStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=signaling.v1.UserStatus" json:"status,omitempty"`
	IsMuted       bool                   `protobuf:"varint,4,opt,name=is_muted,json=isMuted,proto3" json:"is_muted,omitempty"`
	IsVideoOff    bool                   `protobuf:"varint,5,opt,name=is_video_off,json=isVideoOff,proto3" json:"is_video_off,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientStatusRequest) Reset() {
	*x = UpdateClientStatusRequest{}
	mi := &file_signaling_signaling_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientStatusRequest) ProtoMessage() {}

func (x *UpdateClientStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateClientStatusRequest) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateClientStatusRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UpdateClientStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateClientStatusRequest) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

func (x *UpdateClientStatusRequest) GetIsMuted() bool {
	if x != nil {
		return x.IsMuted
	}
	return false
}

func (x *UpdateClientStatusRequest) GetIsVideoOff() bool {
	if x != nil {
		return x.IsVideoOff
	}
	return false
}

type UpdateClientStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClientStatusResponse) Reset() {
	*x = UpdateClientStatusResponse{}
	mi := &file_signaling_signaling_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClientStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClientStatusResponse) ProtoMessage() {}

func (x *UpdateClientStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClientStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateClientStatusResponse) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateClientStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateClientStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveClientRequest) Reset() {
	*x = RemoveClientRequest{}
	mi := &file_signaling_signaling_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveClientRequest) ProtoMessage() {}

func (x *RemoveClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveClientRequest.ProtoReflect.Descriptor instead.
func (*RemoveClientRequest) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{27}
}

func (x *RemoveClientRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveClientRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type RemoveClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveClientResponse) Reset() {
	*x = RemoveClientResponse{}
	mi := &file_signaling_signaling_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveClientResponse) ProtoMessage() {}

func (x *RemoveClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_signaling_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveClientResponse.ProtoReflect.Descriptor instead.
func (*RemoveClientResponse) Descriptor() ([]byte, []int) {
	return file_signaling_signaling_proto_rawDescGZIP(), []int{28}
}

func (x *RemoveClientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveClientResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_signaling_signaling_proto protoreflect.FileDescriptor

const file_signaling_signaling_proto_rawDesc = "" +
	"\n" +
	"\x19signaling/signaling.proto\x12\fsignaling.v1\"\xf5\x03\n" +
	"\x06Client\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12)\n" +
	"\x10user_phonenumber\x18\x04 \x01(\tR\x0fuserPhonenumber\x12*\n" +
	"\x04role\x18\x05 \x01(\x0e2\x16.signaling.v1.UserRoleR\x04role\x120\n" +
	"\x06status\x18\x06 \x01(\x0e2\x18.signaling.v1.UserStatusR\x06status\x12\x1b\n" +
	"\tjoined_at\x18\a \x01(\tR\bjoinedAt\x12 \n" +
	"\flast_seen_at\x18\b \x01(\tR\n" +
	"lastSeenAt\x12>\n" +
	"\bmetadata\x18\t \x03(\v2\".signaling.v1.Client.MetadataEntryR\bmetadata\x12\x1a\n" +
	"\bduration\x18\n" +
	" \x01(\x05R\bduration\x12\x19\n" +
	"\bis_muted\x18\v \x01(\bR\aisMuted\x12 \n" +
	"\fis_video_off\x18\f \x01(\bR\n" +
	"isVideoOff\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x01\n" +
	"\fClientFilter\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12 \n" +
	"\vphonenumber\x18\x04 \x01(\tR\vphonenumber\x12\x12\n" +
	"\x04role\x18\x05 \x01(\x05R\x04role\"\x81\t\n" +
	"\x04Room\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x123\n" +
	"\troom_type\x18\x04 \x01(\x0e2\x16.signaling.v1.RoomTypeR\broomType\x126\n" +
	"\bcategory\x18\x05 \x01(\x0e2\x1a.signaling.v1.RoomCategoryR\bcategory\x120\n" +
	"\x06status\x18\x06 \x01(\x0e2\x18.signaling.v1.RoomStatusR\x06status\x12\x19\n" +
	"\bowner_id\x18\a \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"owner_name\x18\b \x01(\tR\townerName\x12.\n" +
	"\aclients\x18\t \x03(\v2\x14.signaling.v1.ClientR\aclients\x12=\n" +
	"\x0fpending_clients\x18\n" +
	" \x03(\v2\x14.signaling.v1.ClientR\x0ependingClients\x12!\n" +
	"\fonline_count\x18\v \x01(\x05R\vonlineCount\x12)\n" +
	"\x10max_participants\x18\f \x01(\x05R\x0fmaxParticipants\x12\x1d\n" +
	"\n" +
	"is_private\x18\r \x01(\bR\tisPrivate\x12!\n" +
	"\fhas_password\x18\x0e \x01(\bR\vhasPassword\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\x10 \x01(\tR\tstartedAt\x12$\n" +
	"\x0elast_active_at\x18\x11 \x01(\tR\flastActiveAt\x12-\n" +
	"\x12total_participants\x18\x12 \x01(\x05R\x11totalParticipants\x12+\n" +
	"\x11peak_participants\x18\x13 \x01(\x05R\x10peakParticipants\x12(\n" +
	"\x10price_per_minute\x18\x14 \x01(\x02R\x0epricePerMinute\x12\x12\n" +
	"\x04tags\x18\x15 \x03(\tR\x04tags\x12<\n" +
	"\bmetadata\x18\x16 \x03(\v2 .signaling.v1.Room.MetadataEntryR\bmetadata\x12<\n" +
	"\bsettings\x18\x17 \x03(\v2 .signaling.v1.Room.SettingsEntryR\bsettings\x12#\n" +
	"\rthumbnail_url\x18\x18 \x01(\tR\fthumbnailUrl\x12\x16\n" +
	"\x06rating\x18\x19 \x01(\x02R\x06rating\x12!\n" +
	"\freview_count\x18\x1a \x01(\x05R\vreviewCount\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa6\x02\n" +
	"\rSignalMessage\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tfrom_user\x18\x02 \x01(\tR\bfromUser\x12$\n" +
	"\x0efrom_user_name\x18\x03 \x01(\tR\ffromUserName\x12\x17\n" +
	"\ato_user\x18\x04 \x01(\tR\x06toUser\x12 \n" +
	"\fto_user_name\x18\x05 \x01(\tR\n" +
	"toUserName\x12,\n" +
	"\x04type\x18\x06 \x01(\x0e2\x18.signaling.v1.SignalTypeR\x04type\x12\x18\n" +
	"\apayload\x18\a \x01(\tR\apayload\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x03R\ttimestamp\"\x97\x01\n" +
	"\x0fJoinRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x19\n" +
	"\bis_owner\x18\x04 \x01(\bR\aisOwner\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\":\n" +
	"\x10JoinRoomResponse\x12&\n" +
	"\x04room\x18\x01 \x01(\v2\x12.signaling.v1.RoomR\x04room\"H\n" +
	"\x11SendSignalRequest\x123\n" +
	"\x06signal\x18\x01 \x01(\v2\x1b.signaling.v1.SignalMessageR\x06signal\"2\n" +
	"\x12SendSignalResponse\x12\x1c\n" +
	"\tdelivered\x18\x01 \x01(\bR\tdelivered\"D\n" +
	"\x10LeaveRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"-\n" +
	"\x11LeaveRoomResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x97\x03\n" +
	"\n" +
	"RoomFilter\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.signaling.v1.RoomStatusR\x06status\x12\x1f\n" +
	"\vonly_online\x18\x03 \x01(\bR\n" +
	"onlyOnline\x126\n" +
	"\bcategory\x18\x04 \x01(\x0e2\x1a.signaling.v1.RoomCategoryR\bcategory\x123\n" +
	"\troom_type\x18\x05 \x01(\x0e2\x16.signaling.v1.RoomTypeR\broomType\x12\x19\n" +
	"\bowner_id\x18\x06 \x01(\tR\aownerId\x12$\n" +
	"\x0emember_user_id\x18\a \x01(\tR\fmemberUserId\x12!\n" +
	"\fsearch_query\x18\b \x01(\tR\vsearchQuery\x12\x1b\n" +
	"\tmin_price\x18\t \x01(\x02R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\n" +
	" \x01(\x02R\bmaxPrice\x12\x12\n" +
	"\x04tags\x18\v \x03(\tR\x04tags\"\x9c\x03\n" +
	"\x0fGetRoomsRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.signaling.v1.RoomStatusR\x06status\x12\x1f\n" +
	"\vonly_online\x18\x03 \x01(\bR\n" +
	"onlyOnline\x126\n" +
	"\bcategory\x18\x04 \x01(\x0e2\x1a.signaling.v1.RoomCategoryR\bcategory\x123\n" +
	"\troom_type\x18\x05 \x01(\x0e2\x16.signaling.v1.RoomTypeR\broomType\x12\x19\n" +
	"\bowner_id\x18\x06 \x01(\tR\aownerId\x12$\n" +
	"\x0emember_user_id\x18\a \x01(\tR\fmemberUserId\x12!\n" +
	"\fsearch_query\x18\b \x01(\tR\vsearchQuery\x12\x1b\n" +
	"\tmin_price\x18\t \x01(\x02R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\n" +
	" \x01(\x02R\bmaxPrice\x12\x12\n" +
	"\x04tags\x18\v \x03(\tR\x04tags\"\x85\x01\n" +
	"\x10GetRoomsResponse\x12&\n" +
	"\x04room\x18\x01 \x01(\v2\x12.signaling.v1.RoomR\x04room\x12(\n" +
	"\x05rooms\x18\x02 \x03(\v2\x12.signaling.v1.RoomR\x05rooms\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\xc8\x04\n" +
	"\x11CreateRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x123\n" +
	"\troom_type\x18\x04 \x01(\x0e2\x16.signaling.v1.RoomTypeR\broomType\x126\n" +
	"\bcategory\x18\x05 \x01(\x0e2\x1a.signaling.v1.RoomCategoryR\bcategory\x12)\n" +
	"\x10max_participants\x18\x06 \x01(\x05R\x0fmaxParticipants\x12\x1d\n" +
	"\n" +
	"is_private\x18\a \x01(\bR\tisPrivate\x12\x1a\n" +
	"\bpassword\x18\b \x01(\tR\bpassword\x12I\n" +
	"\bsettings\x18\t \x03(\v2-.signaling.v1.CreateRoomRequest.SettingsEntryR\bsettings\x12(\n" +
	"\x10price_per_minute\x18\n" +
	" \x01(\x02R\x0epricePerMinute\x12\x12\n" +
	"\x04tags\x18\v \x03(\tR\x04tags\x12\x19\n" +
	"\bowner_id\x18\f \x01(\tR\aownerId\x120\n" +
	"\x06status\x18\r \x01(\x0e2\x18.signaling.v1.RoomStatusR\x06status\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\x12CreateRoomResponse\x12&\n" +
	"\x04room\x18\x01 \x01(\v2\x12.signaling.v1.RoomR\x04room\"\xef\x03\n" +
	"\x19UpdateRoomSettingsRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x126\n" +
	"\bcategory\x18\x05 \x01(\x0e2\x1a.signaling.v1.RoomCategoryR\bcategory\x12)\n" +
	"\x10max_participants\x18\x06 \x01(\x05R\x0fmaxParticipants\x12\x1d\n" +
	"\n" +
	"is_private\x18\a \x01(\bR\tisPrivate\x12\x1a\n" +
	"\bpassword\x18\b \x01(\tR\bpassword\x12Q\n" +
	"\bsettings\x18\t \x03(\v25.signaling.v1.UpdateRoomSettingsRequest.SettingsEntryR\bsettings\x12(\n" +
	"\x10price_per_minute\x18\n" +
	" \x01(\x02R\x0epricePerMinute\x12\x12\n" +
	"\x04tags\x18\v \x03(\tR\x04tags\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\x1aUpdateRoomSettingsResponse\x12&\n" +
	"\x04room\x18\x01 \x01(\v2\x12.signaling.v1.RoomR\x04room\"D\n" +
	"\x10CloseRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"G\n" +
	"\x11CloseRoomResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"E\n" +
	"\x11RemoveRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"H\n" +
	"\x12RemoveRoomResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xdb\x01\n" +
	"\x13CreateClientRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12 \n" +
	"\vphonenumber\x18\x04 \x01(\tR\vphonenumber\x12*\n" +
	"\x04role\x18\x05 \x01(\x0e2\x16.signaling.v1.UserRoleR\x04role\x120\n" +
	"\x06status\x18\x06 \x01(\x0e2\x18.signaling.v1.UserStatusR\x06status\"D\n" +
	"\x14CreateClientResponse\x12,\n" +
	"\x06client\x18\x01 \x01(\v2\x14.signaling.v1.ClientR\x06client\"K\n" +
	"\x15GetRoomClientsRequest\x122\n" +
	"\x06filter\x18\x01 \x01(\v2\x1a.signaling.v1.ClientFilterR\x06filter\"\xcb\x01\n" +
	"\x16GetRoomClientsResponse\x12.\n" +
	"\aclients\x18\x01 \x03(\v2\x14.signaling.v1.ClientR\aclients\x12=\n" +
	"\x0fpending_clients\x18\x02 \x03(\v2\x14.signaling.v1.ClientR\x0ependingClients\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12!\n" +
	"\fonline_count\x18\x04 \x01(\x05R\vonlineCount\"\xbc\x01\n" +
	"\x19UpdateClientStatusRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x120\n" +
	"\x06status\x18\x03 \x01(\x0e2\x18.signaling.v1.UserStatusR\x06status\x12\x19\n" +
	"\bis_muted\x18\x04 \x01(\bR\aisMuted\x12 \n" +
	"\fis_video_off\x18\x05 \x01(\bR\n" +
	"isVideoOff\"P\n" +
	"\x1aUpdateClientStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"G\n" +
	"\x13RemoveClientRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"J\n" +
	"\x14RemoveClientResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xaa\x03\n" +
	"\n" +
	"SignalType\x12\x1b\n" +
	"\x17SIGNAL_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SIGNAL_TYPE_OFFER\x10\x01\x12\x16\n" +
	"\x12SIGNAL_TYPE_ANSWER\x10\x02\x12\x19\n" +
	"\x15SIGNAL_TYPE_CANDIDATE\x10\x03\x12\x15\n" +
	"\x11SIGNAL_TYPE_LEAVE\x10\x04\x12\x14\n" +
	"\x10SIGNAL_TYPE_CHAT\x10\x05\x12\x16\n" +
	"\x12SIGNAL_USER_JOINED\x10\x06\x12\x1c\n" +
	"\x18SIGNAL_TYPE_REQUEST_JOIN\x10\a\x12\x1c\n" +
	"\x18SIGNAL_TYPE_APPROVE_JOIN\x10\b\x12\x1b\n" +
	"\x17SIGNAL_TYPE_REJECT_JOIN\x10\t\x12\x1a\n" +
	"\x16SIGNAL_TYPE_OWNER_LEFT\x10\n" +
	"\x12\x19\n" +
	"\x15SIGNAL_TYPE_ROOM_INFO\x10\v\x12\x1d\n" +
	"\x19SIGNAL_TYPE_PENDING_USERS\x10\f\x12\x1c\n" +
	"\x18SIGNAL_TYPE_ROOM_UPDATED\x10\r\x12#\n" +
	"\x1fSIGNAL_TYPE_USER_STATUS_CHANGED\x10\x0e*\x83\x01\n" +
	"\bRoomType\x12\x19\n" +
	"\x15ROOM_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eROOM_TYPE_PEER\x10\x01\x12\x1a\n" +
	"\x16ROOM_TYPE_CONSULTATION\x10\x02\x12\x17\n" +
	"\x13ROOM_TYPE_BROADCAST\x10\x03\x12\x13\n" +
	"\x0fROOM_TYPE_GROUP\x10\x04*\x8d\x01\n" +
	"\n" +
	"RoomStatus\x12\x1b\n" +
	"\x17ROOM_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ROOM_STATUS_ACTIVE\x10\x01\x12\x18\n" +
	"\x14ROOM_STATUS_INACTIVE\x10\x02\x12\x16\n" +
	"\x12ROOM_STATUS_CLOSED\x10\x03\x12\x18\n" +
	"\x14ROOM_STATUS_ARCHIVED\x10\x04*\xe7\x01\n" +
	"\fRoomCategory\x12\x1d\n" +
	"\x19ROOM_CATEGORY_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ROOM_CATEGORY_MEDICAL\x10\x01\x12\"\n" +
	"\x1eROOM_CATEGORY_SKIN_HAIR_BEAUTY\x10\x02\x12\x1e\n" +
	"\x1aROOM_CATEGORY_LASER_BEAUTY\x10\x03\x12!\n" +
	"\x1dROOM_CATEGORY_COSMETIC_BEAUTY\x10\x04\x12\x1d\n" +
	"\x19ROOM_CATEGORY_EDUCATIONAL\x10\x05\x12\x17\n" +
	"\x13ROOM_CATEGORY_OTHER\x10\x06*\x85\x01\n" +
	"\bUserRole\x12\x19\n" +
	"\x15USER_ROLE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fUSER_ROLE_OWNER\x10\x01\x12\x19\n" +
	"\x15USER_ROLE_PARTICIPANT\x10\x02\x12\x15\n" +
	"\x11USER_ROLE_PENDING\x10\x03\x12\x17\n" +
	"\x13USER_ROLE_MODERATOR\x10\x04*p\n" +
	"\n" +
	"UserStatus\x12\x1b\n" +
	"\x17USER_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12USER_STATUS_ONLINE\x10\x01\x12\x17\n" +
	"\x13USER_STATUS_OFFLINE\x10\x02\x12\x14\n" +
	"\x10USER_STATUS_AWAY\x10\x032\x93\b\n" +
	"\x10SignalingService\x12H\n" +
	"\bJoinRoom\x12\x1d.signaling.v1.JoinRoomRequest\x1a\x1b.signaling.v1.SignalMessage0\x01\x12O\n" +
	"\n" +
	"SendSignal\x12\x1f.signaling.v1.SendSignalRequest\x1a .signaling.v1.SendSignalResponse\x12L\n" +
	"\tLeaveRoom\x12\x1e.signaling.v1.LeaveRoomRequest\x1a\x1f.signaling.v1.LeaveRoomResponse\x12O\n" +
	"\n" +
	"CreateRoom\x12\x1f.signaling.v1.CreateRoomRequest\x1a .signaling.v1.CreateRoomResponse\x12I\n" +
	"\bGetRooms\x12\x1d.signaling.v1.GetRoomsRequest\x1a\x1e.signaling.v1.GetRoomsResponse\x12g\n" +
	"\x12UpdateRoomSettings\x12'.signaling.v1.UpdateRoomSettingsRequest\x1a(.signaling.v1.UpdateRoomSettingsResponse\x12L\n" +
	"\tCloseRoom\x12\x1e.signaling.v1.CloseRoomRequest\x1a\x1f.signaling.v1.CloseRoomResponse\x12O\n" +
	"\n" +
	"RemoveRoom\x12\x1f.signaling.v1.RemoveRoomRequest\x1a .signaling.v1.RemoveRoomResponse\x12U\n" +
	"\fCreateClient\x12!.signaling.v1.CreateClientRequest\x1a\".signaling.v1.CreateClientResponse\x12[\n" +
	"\x0eGetRoomClients\x12#.signaling.v1.GetRoomClientsRequest\x1a$.signaling.v1.GetRoomClientsResponse\x12g\n" +
	"\x12UpdateClientStatus\x12'.signaling.v1.UpdateClientStatusRequest\x1a(.signaling.v1.UpdateClientStatusResponse\x12U\n" +
	"\fRemoveClient\x12!.signaling.v1.RemoveClientRequest\x1a\".signaling.v1.RemoveClientResponseBKZIgithub.com/az58740/connect-microservices-proto/golang/signaling;signalingb\x06proto3"

var (
	file_signaling_signaling_proto_rawDescOnce sync.Once
	file_signaling_signaling_proto_rawDescData []byte
)

func file_signaling_signaling_proto_rawDescGZIP() []byte {
	file_signaling_signaling_proto_rawDescOnce.Do(func() {
		file_signaling_signaling_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_signaling_signaling_proto_rawDesc), len(file_signaling_signaling_proto_rawDesc)))
	})
	return file_signaling_signaling_proto_rawDescData
}

var file_signaling_signaling_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_signaling_signaling_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_signaling_signaling_proto_goTypes = []any{
	(SignalType)(0),                    // 0: signaling.v1.SignalType
	(RoomType)(0),                      // 1: signaling.v1.RoomType
	(RoomStatus)(0),                    // 2: signaling.v1.RoomStatus
	(RoomCategory)(0),                  // 3: signaling.v1.RoomCategory
	(UserRole)(0),                      // 4: signaling.v1.UserRole
	(UserStatus)(0),                    // 5: signaling.v1.UserStatus
	(*Client)(nil),                     // 6: signaling.v1.Client
	(*ClientFilter)(nil),               // 7: signaling.v1.ClientFilter
	(*Room)(nil),                       // 8: signaling.v1.Room
	(*SignalMessage)(nil),              // 9: signaling.v1.SignalMessage
	(*JoinRoomRequest)(nil),            // 10: signaling.v1.JoinRoomRequest
	(*JoinRoomResponse)(nil),           // 11: signaling.v1.JoinRoomResponse
	(*SendSignalRequest)(nil),          // 12: signaling.v1.SendSignalRequest
	(*SendSignalResponse)(nil),         // 13: signaling.v1.SendSignalResponse
	(*LeaveRoomRequest)(nil),           // 14: signaling.v1.LeaveRoomRequest
	(*LeaveRoomResponse)(nil),          // 15: signaling.v1.LeaveRoomResponse
	(*RoomFilter)(nil),                 // 16: signaling.v1.RoomFilter
	(*GetRoomsRequest)(nil),            // 17: signaling.v1.GetRoomsRequest
	(*GetRoomsResponse)(nil),           // 18: signaling.v1.GetRoomsResponse
	(*CreateRoomRequest)(nil),          // 19: signaling.v1.CreateRoomRequest
	(*CreateRoomResponse)(nil),         // 20: signaling.v1.CreateRoomResponse
	(*UpdateRoomSettingsRequest)(nil),  // 21: signaling.v1.UpdateRoomSettingsRequest
	(*UpdateRoomSettingsResponse)(nil), // 22: signaling.v1.UpdateRoomSettingsResponse
	(*CloseRoomRequest)(nil),           // 23: signaling.v1.CloseRoomRequest
	(*CloseRoomResponse)(nil),          // 24: signaling.v1.CloseRoomResponse
	(*RemoveRoomRequest)(nil),          // 25: signaling.v1.RemoveRoomRequest
	(*RemoveRoomResponse)(nil),         // 26: signaling.v1.RemoveRoomResponse
	(*CreateClientRequest)(nil),        // 27: signaling.v1.CreateClientRequest
	(*CreateClientResponse)(nil),       // 28: signaling.v1.CreateClientResponse
	(*GetRoomClientsRequest)(nil),      // 29: signaling.v1.GetRoomClientsRequest
	(*GetRoomClientsResponse)(nil),     // 30: signaling.v1.GetRoomClientsResponse
	(*UpdateClientStatusRequest)(nil),  // 31: signaling.v1.UpdateClientStatusRequest
	(*UpdateClientStatusResponse)(nil), // 32: signaling.v1.UpdateClientStatusResponse
	(*RemoveClientRequest)(nil),        // 33: signaling.v1.RemoveClientRequest
	(*RemoveClientResponse)(nil),       // 34: signaling.v1.RemoveClientResponse
	nil,                                // 35: signaling.v1.Client.MetadataEntry
	nil,                                // 36: signaling.v1.Room.MetadataEntry
	nil,                                // 37: signaling.v1.Room.SettingsEntry
	nil,                                // 38: signaling.v1.CreateRoomRequest.SettingsEntry
	nil,                                // 39: signaling.v1.UpdateRoomSettingsRequest.SettingsEntry
}
var file_signaling_signaling_proto_depIdxs = []int32{
	4,  // 0: signaling.v1.Client.role:type_name -> signaling.v1.UserRole
	5,  // 1: signaling.v1.Client.status:type_name -> signaling.v1.UserStatus
	35, // 2: signaling.v1.Client.metadata:type_name -> signaling.v1.Client.MetadataEntry
	1,  // 3: signaling.v1.Room.room_type:type_name -> signaling.v1.RoomType
	3,  // 4: signaling.v1.Room.category:type_name -> signaling.v1.RoomCategory
	2,  // 5: signaling.v1.Room.status:type_name -> signaling.v1.RoomStatus
	6,  // 6: signaling.v1.Room.clients:type_name -> signaling.v1.Client
	6,  // 7: signaling.v1.Room.pending_clients:type_name -> signaling.v1.Client
	36, // 8: signaling.v1.Room.metadata:type_name -> signaling.v1.Room.MetadataEntry
	37, // 9: signaling.v1.Room.settings:type_name -> signaling.v1.Room.SettingsEntry
	0,  // 10: signaling.v1.SignalMessage.type:type_name -> signaling.v1.SignalType
	8,  // 11: signaling.v1.JoinRoomResponse.room:type_name -> signaling.v1.Room
	9,  // 12: signaling.v1.SendSignalRequest.signal:type_name -> signaling.v1.SignalMessage
	2,  // 13: signaling.v1.RoomFilter.status:type_name -> signaling.v1.RoomStatus
	3,  // 14: signaling.v1.RoomFilter.category:type_name -> signaling.v1.RoomCategory
	1,  // 15: signaling.v1.RoomFilter.room_type:type_name -> signaling.v1.RoomType
	2,  // 16: signaling.v1.GetRoomsRequest.status:type_name -> signaling.v1.RoomStatus
	3,  // 17: signaling.v1.GetRoomsRequest.category:type_name -> signaling.v1.RoomCategory
	1,  // 18: signaling.v1.GetRoomsRequest.room_type:type_name -> signaling.v1.RoomType
	8,  // 19: signaling.v1.GetRoomsResponse.room:type_name -> signaling.v1.Room
	8,  // 20: signaling.v1.GetRoomsResponse.rooms:type_name -> signaling.v1.Room
	1,  // 21: signaling.v1.CreateRoomRequest.room_type:type_name -> signaling.v1.RoomType
	3,  // 22: signaling.v1.CreateRoomRequest.category:type_name -> signaling.v1.RoomCategory
	38, // 23: signaling.v1.CreateRoomRequest.settings:type_name -> signaling.v1.CreateRoomRequest.SettingsEntry
	2,  // 24: signaling.v1.CreateRoomRequest.status:type_name -> signaling.v1.RoomStatus
	8,  // 25: signaling.v1.CreateRoomResponse.room:type_name -> signaling.v1.Room
	3,  // 26: signaling.v1.UpdateRoomSettingsRequest.category:type_name -> signaling.v1.RoomCategory
	39, // 27: signaling.v1.UpdateRoomSettingsRequest.settings:type_name -> signaling.v1.UpdateRoomSettingsRequest.SettingsEntry
	8,  // 28: signaling.v1.UpdateRoomSettingsResponse.room:type_name -> signaling.v1.Room
	4,  // 29: signaling.v1.CreateClientRequest.role:type_name -> signaling.v1.UserRole
	5,  // 30: signaling.v1.CreateClientRequest.status:type_name -> signaling.v1.UserStatus
	6,  // 31: signaling.v1.CreateClientResponse.client:type_name -> signaling.v1.Client
	7,  // 32: signaling.v1.GetRoomClientsRequest.filter:type_name -> signaling.v1.ClientFilter
	6,  // 33: signaling.v1.GetRoomClientsResponse.clients:type_name -> signaling.v1.Client
	6,  // 34: signaling.v1.GetRoomClientsResponse.pending_clients:type_name -> signaling.v1.Client
	5,  // 35: signaling.v1.UpdateClientStatusRequest.status:type_name -> signaling.v1.UserStatus
	10, // 36: signaling.v1.SignalingService.JoinRoom:input_type -> signaling.v1.JoinRoomRequest
	12, // 37: signaling.v1.SignalingService.SendSignal:input_type -> signaling.v1.SendSignalRequest
	14, // 38: signaling.v1.SignalingService.LeaveRoom:input_type -> signaling.v1.LeaveRoomRequest
	19, // 39: signaling.v1.SignalingService.CreateRoom:input_type -> signaling.v1.CreateRoomRequest
	17, // 40: signaling.v1.SignalingService.GetRooms:input_type -> signaling.v1.GetRoomsRequest
	21, // 41: signaling.v1.SignalingService.UpdateRoomSettings:input_type -> signaling.v1.UpdateRoomSettingsRequest
	23, // 42: signaling.v1.SignalingService.CloseRoom:input_type -> signaling.v1.CloseRoomRequest
	25, // 43: signaling.v1.SignalingService.RemoveRoom:input_type -> signaling.v1.RemoveRoomRequest
	27, // 44: signaling.v1.SignalingService.CreateClient:input_type -> signaling.v1.CreateClientRequest
	29, // 45: signaling.v1.SignalingService.GetRoomClients:input_type -> signaling.v1.GetRoomClientsRequest
	31, // 46: signaling.v1.SignalingService.UpdateClientStatus:input_type -> signaling.v1.UpdateClientStatusRequest
	33, // 47: signaling.v1.SignalingService.RemoveClient:input_type -> signaling.v1.RemoveClientRequest
	9,  // 48: signaling.v1.SignalingService.JoinRoom:output_type -> signaling.v1.SignalMessage
	13, // 49: signaling.v1.SignalingService.SendSignal:output_type -> signaling.v1.SendSignalResponse
	15, // 50: signaling.v1.SignalingService.LeaveRoom:output_type -> signaling.v1.LeaveRoomResponse
	20, // 51: signaling.v1.SignalingService.CreateRoom:output_type -> signaling.v1.CreateRoomResponse
	18, // 52: signaling.v1.SignalingService.GetRooms:output_type -> signaling.v1.GetRoomsResponse
	22, // 53: signaling.v1.SignalingService.UpdateRoomSettings:output_type -> signaling.v1.UpdateRoomSettingsResponse
	24, // 54: signaling.v1.SignalingService.CloseRoom:output_type -> signaling.v1.CloseRoomResponse
	26, // 55: signaling.v1.SignalingService.RemoveRoom:output_type -> signaling.v1.RemoveRoomResponse
	28, // 56: signaling.v1.SignalingService.CreateClient:output_type -> signaling.v1.CreateClientResponse
	30, // 57: signaling.v1.SignalingService.GetRoomClients:output_type -> signaling.v1.GetRoomClientsResponse
	32, // 58: signaling.v1.SignalingService.UpdateClientStatus:output_type -> signaling.v1.UpdateClientStatusResponse
	34, // 59: signaling.v1.SignalingService.RemoveClient:output_type -> signaling.v1.RemoveClientResponse
	48, // [48:60] is the sub-list for method output_type
	36, // [36:48] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_signaling_signaling_proto_init() }
func file_signaling_signaling_proto_init() {
	if File_signaling_signaling_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_signaling_signaling_proto_rawDesc), len(file_signaling_signaling_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_signaling_signaling_proto_goTypes,
		DependencyIndexes: file_signaling_signaling_proto_depIdxs,
		EnumInfos:         file_signaling_signaling_proto_enumTypes,
		MessageInfos:      file_signaling_signaling_proto_msgTypes,
	}.Build()
	File_signaling_signaling_proto = out.File
	file_signaling_signaling_proto_goTypes = nil
	file_signaling_signaling_proto_depIdxs = nil
}
