// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: reservations/reservation.proto

package reservationsconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	reservations "github.com/az58740/connect-microservices-proto/golang/reservations"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ReservationServiceName is the fully-qualified name of the ReservationService service.
	ReservationServiceName = "reservation.ReservationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ReservationServiceCreateFacilityProcedure is the fully-qualified name of the ReservationService's
	// CreateFacility RPC.
	ReservationServiceCreateFacilityProcedure = "/reservation.ReservationService/CreateFacility"
	// ReservationServiceUpdateFacilityProcedure is the fully-qualified name of the ReservationService's
	// UpdateFacility RPC.
	ReservationServiceUpdateFacilityProcedure = "/reservation.ReservationService/UpdateFacility"
	// ReservationServiceListFacilitiesProcedure is the fully-qualified name of the ReservationService's
	// ListFacilities RPC.
	ReservationServiceListFacilitiesProcedure = "/reservation.ReservationService/ListFacilities"
	// ReservationServiceCreateServiceProcedure is the fully-qualified name of the ReservationService's
	// CreateService RPC.
	ReservationServiceCreateServiceProcedure = "/reservation.ReservationService/CreateService"
	// ReservationServiceUpdateServiceProcedure is the fully-qualified name of the ReservationService's
	// UpdateService RPC.
	ReservationServiceUpdateServiceProcedure = "/reservation.ReservationService/UpdateService"
	// ReservationServiceListServicesProcedure is the fully-qualified name of the ReservationService's
	// ListServices RPC.
	ReservationServiceListServicesProcedure = "/reservation.ReservationService/ListServices"
	// ReservationServiceAssignServiceToProviderProcedure is the fully-qualified name of the
	// ReservationService's AssignServiceToProvider RPC.
	ReservationServiceAssignServiceToProviderProcedure = "/reservation.ReservationService/AssignServiceToProvider"
	// ReservationServiceRemoveServiceFromProviderProcedure is the fully-qualified name of the
	// ReservationService's RemoveServiceFromProvider RPC.
	ReservationServiceRemoveServiceFromProviderProcedure = "/reservation.ReservationService/RemoveServiceFromProvider"
	// ReservationServiceGetProviderServicesListProcedure is the fully-qualified name of the
	// ReservationService's GetProviderServicesList RPC.
	ReservationServiceGetProviderServicesListProcedure = "/reservation.ReservationService/GetProviderServicesList"
	// ReservationServiceUpdateProviderServiceProcedure is the fully-qualified name of the
	// ReservationService's UpdateProviderService RPC.
	ReservationServiceUpdateProviderServiceProcedure = "/reservation.ReservationService/UpdateProviderService"
	// ReservationServiceCreateWeeklyScheduleProcedure is the fully-qualified name of the
	// ReservationService's CreateWeeklySchedule RPC.
	ReservationServiceCreateWeeklyScheduleProcedure = "/reservation.ReservationService/CreateWeeklySchedule"
	// ReservationServiceGetWeeklyScheduleListProcedure is the fully-qualified name of the
	// ReservationService's GetWeeklyScheduleList RPC.
	ReservationServiceGetWeeklyScheduleListProcedure = "/reservation.ReservationService/GetWeeklyScheduleList"
	// ReservationServiceUpdateWeeklyScheduleProcedure is the fully-qualified name of the
	// ReservationService's UpdateWeeklySchedule RPC.
	ReservationServiceUpdateWeeklyScheduleProcedure = "/reservation.ReservationService/UpdateWeeklySchedule"
	// ReservationServiceRemoveWeeklyScheduleProcedure is the fully-qualified name of the
	// ReservationService's RemoveWeeklySchedule RPC.
	ReservationServiceRemoveWeeklyScheduleProcedure = "/reservation.ReservationService/RemoveWeeklySchedule"
	// ReservationServiceGenerateTimeSlotsProcedure is the fully-qualified name of the
	// ReservationService's GenerateTimeSlots RPC.
	ReservationServiceGenerateTimeSlotsProcedure = "/reservation.ReservationService/GenerateTimeSlots"
	// ReservationServiceGetTimeSlotsListProcedure is the fully-qualified name of the
	// ReservationService's GetTimeSlotsList RPC.
	ReservationServiceGetTimeSlotsListProcedure = "/reservation.ReservationService/GetTimeSlotsList"
	// ReservationServiceUpdateTimeSlotProcedure is the fully-qualified name of the ReservationService's
	// UpdateTimeSlot RPC.
	ReservationServiceUpdateTimeSlotProcedure = "/reservation.ReservationService/UpdateTimeSlot"
	// ReservationServiceRemoveTimeSlotsProcedure is the fully-qualified name of the
	// ReservationService's RemoveTimeSlots RPC.
	ReservationServiceRemoveTimeSlotsProcedure = "/reservation.ReservationService/RemoveTimeSlots"
	// ReservationServiceCreateReservationProcedure is the fully-qualified name of the
	// ReservationService's CreateReservation RPC.
	ReservationServiceCreateReservationProcedure = "/reservation.ReservationService/CreateReservation"
	// ReservationServiceUpdateReservationStatusProcedure is the fully-qualified name of the
	// ReservationService's UpdateReservationStatus RPC.
	ReservationServiceUpdateReservationStatusProcedure = "/reservation.ReservationService/UpdateReservationStatus"
	// ReservationServiceListReservationsProcedure is the fully-qualified name of the
	// ReservationService's ListReservations RPC.
	ReservationServiceListReservationsProcedure = "/reservation.ReservationService/ListReservations"
	// ReservationServiceRemoveReservationProcedure is the fully-qualified name of the
	// ReservationService's RemoveReservation RPC.
	ReservationServiceRemoveReservationProcedure = "/reservation.ReservationService/RemoveReservation"
	// ReservationServiceCreateCustomerProcedure is the fully-qualified name of the ReservationService's
	// CreateCustomer RPC.
	ReservationServiceCreateCustomerProcedure = "/reservation.ReservationService/CreateCustomer"
	// ReservationServiceUpdateCustomerProcedure is the fully-qualified name of the ReservationService's
	// UpdateCustomer RPC.
	ReservationServiceUpdateCustomerProcedure = "/reservation.ReservationService/UpdateCustomer"
	// ReservationServiceListCustomerProcedure is the fully-qualified name of the ReservationService's
	// ListCustomer RPC.
	ReservationServiceListCustomerProcedure = "/reservation.ReservationService/ListCustomer"
	// ReservationServiceGetProviderServicesWithUsersProcedure is the fully-qualified name of the
	// ReservationService's GetProviderServicesWithUsers RPC.
	ReservationServiceGetProviderServicesWithUsersProcedure = "/reservation.ReservationService/GetProviderServicesWithUsers"
	// ReservationServiceProcessAudioProcedure is the fully-qualified name of the ReservationService's
	// ProcessAudio RPC.
	ReservationServiceProcessAudioProcedure = "/reservation.ReservationService/ProcessAudio"
)

// ReservationServiceClient is a client for the reservation.ReservationService service.
type ReservationServiceClient interface {
	// facility related methods
	// ایجاد یک فسیلیتی جدید | Create a new facility
	CreateFacility(context.Context, *connect.Request[reservations.CreateFacilityRequest]) (*connect.Response[reservations.CreateFacilityResponse], error)
	// ویرایش یم فسیلیتی| update a  facility
	UpdateFacility(context.Context, *connect.Request[reservations.UpdateFacilityRequest]) (*connect.Response[reservations.UpdateFacilityResponse], error)
	// دریافت لیست مکان‌ها | List all facilities
	ListFacilities(context.Context, *connect.Request[reservations.ListFacilitiesRequest]) (*connect.Response[reservations.ListFacilitiesResponse], error)
	// Service related methods
	// ایجاد سرویس جدید برای یک فسیلیتی | Create a new service for a facility
	CreateService(context.Context, *connect.Request[reservations.CreateServiceRequest]) (*connect.Response[reservations.CreateServiceResponse], error)
	// ویرایش سرویس  | Update a service for a facility
	UpdateService(context.Context, *connect.Request[reservations.UpdateServiceRequest]) (*connect.Response[reservations.UpdateServiceResponse], error)
	// دریافت لیست سرویس‌های یک فسیلیتی | List services of a facility
	ListServices(context.Context, *connect.Request[reservations.ListServicesRequest]) (*connect.Response[reservations.ListServicesResponse], error)
	// ُProvider Service  related methods
	// تخصیص یک سرویس به ارائه‌دهنده | Assign a service to a provider
	AssignServiceToProvider(context.Context, *connect.Request[reservations.AssignServiceToProviderRequest]) (*connect.Response[reservations.AssignServiceToProviderResponse], error)
	// خذف یک سرویس از ارائه‌دهنده | Remove a service from a provider
	RemoveServiceFromProvider(context.Context, *connect.Request[reservations.RemoveServiceFromProviderRequest]) (*connect.Response[reservations.RemoveServiceFromProviderResponse], error)
	// دریافت لیست سرویس‌های یک ارائه‌دهنده| Get provider services
	GetProviderServicesList(context.Context, *connect.Request[reservations.GetProviderServicesListRequest]) (*connect.Response[reservations.GetProviderServicesListResponse], error)
	// ویرایش سرویس  | Update a service for a provider
	UpdateProviderService(context.Context, *connect.Request[reservations.UpdateProviderServiceRequest]) (*connect.Response[reservations.UpdateProviderServiceResponse], error)
	// WeeklySchedule and TimeSlot releated methods
	// ایجاد برنامه‌ زمانی هفتگی برای ارائه‌دهنده | Create weekly schedule for provider
	CreateWeeklySchedule(context.Context, *connect.Request[reservations.CreateWeeklyScheduleRequest]) (*connect.Response[reservations.CreateWeeklyScheduleResponse], error)
	GetWeeklyScheduleList(context.Context, *connect.Request[reservations.GetWeeklyScheduleListRequest]) (*connect.Response[reservations.GetWeeklyScheduleListResponse], error)
	UpdateWeeklySchedule(context.Context, *connect.Request[reservations.UpdateWeeklyScheduleRequest]) (*connect.Response[reservations.UpdateWeeklyScheduleResponse], error)
	RemoveWeeklySchedule(context.Context, *connect.Request[reservations.RemoveWeeklyScheduleRequest]) (*connect.Response[reservations.RemoveWeeklyScheduleResponse], error)
	// تولید تایم‌اسلات‌ها بر اساس برنامه‌ هفتگی | Generate time slots from weekly schedule
	GenerateTimeSlots(context.Context, *connect.Request[reservations.GenerateTimeSlotsRequest]) (*connect.Response[reservations.GenerateTimeSlotsResponse], error)
	GetTimeSlotsList(context.Context, *connect.Request[reservations.GetTimeSlotsListRequest]) (*connect.Response[reservations.GetTimeSlotsListResponse], error)
	UpdateTimeSlot(context.Context, *connect.Request[reservations.UpdateTimeSlotRequest]) (*connect.Response[reservations.UpdateTimeSlotResponse], error)
	RemoveTimeSlots(context.Context, *connect.Request[reservations.RemoveTimeSlotsRequest]) (*connect.Response[reservations.RemoveTimeSlotsResponse], error)
	// 🔹  رزرو | Reservation
	CreateReservation(context.Context, *connect.Request[reservations.CreateReservationRequest]) (*connect.Response[reservations.CreateReservationResponse], error)
	UpdateReservationStatus(context.Context, *connect.Request[reservations.UpdateReservationRequest]) (*connect.Response[reservations.UpdateReservationResponse], error)
	ListReservations(context.Context, *connect.Request[reservations.ListReservationsRequest]) (*connect.Response[reservations.ListReservationsResponse], error)
	RemoveReservation(context.Context, *connect.Request[reservations.DeleteReservationRequest]) (*connect.Response[reservations.DeleteReservationResponse], error)
	// 🔹  Customer
	CreateCustomer(context.Context, *connect.Request[reservations.CreateCustomerRequest]) (*connect.Response[reservations.CreateCustomerResponse], error)
	UpdateCustomer(context.Context, *connect.Request[reservations.UpdateCustomerRequest]) (*connect.Response[reservations.UpdateCustomerResponse], error)
	ListCustomer(context.Context, *connect.Request[reservations.ListCustomerRequest]) (*connect.Response[reservations.ListCustomerResponse], error)
	// DOT
	GetProviderServicesWithUsers(context.Context, *connect.Request[reservations.GetProviderServicesWithUsersRequest]) (*connect.Response[reservations.GetProviderServicesWithUsersResponse], error)
	// پردازش یک فایل صوتی و برگرداندن متن و فیلترها
	// برای شروع ساده: درخواست تک با بایت‌های فایل (مناسب برای فایلی تا چندین مگ)
	ProcessAudio(context.Context, *connect.Request[reservations.ProcessAudioRequest]) (*connect.Response[reservations.ProcessAudioResponse], error)
}

// NewReservationServiceClient constructs a client for the reservation.ReservationService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewReservationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ReservationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	reservationServiceMethods := reservations.File_reservations_reservation_proto.Services().ByName("ReservationService").Methods()
	return &reservationServiceClient{
		createFacility: connect.NewClient[reservations.CreateFacilityRequest, reservations.CreateFacilityResponse](
			httpClient,
			baseURL+ReservationServiceCreateFacilityProcedure,
			connect.WithSchema(reservationServiceMethods.ByName("CreateFacility")),
			connect.WithClientOptions(opts...),
		),
		updateFacility: connect.NewClient[reservations.UpdateFacilityRequest, reservations.UpdateFacilityResponse](
			httpClient,
			baseURL+ReservationServiceUpdateFacilityProcedure,
			connect.WithSchema(reservationServiceMethods.ByName("UpdateFacility")),
			connect.WithClientOptions(opts...),
		),
		listFacilities: connect.NewClient[reservations.ListFacilitiesRequest, reservations.ListFacilitiesResponse](
			httpClient,
			baseURL+ReservationServiceListFacilitiesProcedure,
			connect.WithSchema(reservationServiceMethods.ByName("ListFacilities")),
			connect.WithClientOptions(opts...),
		),
		createService: connect.NewClient[reservations.CreateServiceRequest, reservations.CreateServiceResponse](
			httpClient,
			baseURL+ReservationServiceCreateServiceProcedure,
			connect.WithSchema(reservationServiceMethods.ByName("CreateService")),
			connect.WithClientOptions(opts...),
		),
		updateService: connect.NewClient[reservations.UpdateServiceRequest, reservations.UpdateServiceResponse](
			httpClient,
			baseURL+ReservationServiceUpdateServiceProcedure,
			connect.WithSchema(reservationServiceMethods.ByName("UpdateService")),
			connect.WithClientOptions(opts...),
		),
		listServices: connect.NewClient[reservations.ListServicesRequest, reservations.ListServicesResponse](
			httpClient,
			baseURL+ReservationServiceListServicesProcedure,
			connect.WithSchema(reservationServiceMethods.ByName("ListServices")),
			connect.WithClientOptions(opts...),
		),
		assignServiceToProvider: connect.NewClient[reservations.AssignServiceToProviderRequest, reservations.AssignServiceToProviderResponse](
			httpClient,
			baseURL+ReservationServiceAssignServiceToProviderProcedure,
			connect.WithSchema(reservationServiceMethods.ByName("AssignServiceToProvider")),
			connect.WithClientOptions(opts...),
		),
		removeServiceFromProvider: connect.NewClient[reservations.RemoveServiceFromProviderRequest, reservations.RemoveServiceFromProviderResponse](
			httpClient,
			baseURL+ReservationServiceRemoveServiceFromProviderProcedure,
			connect.WithSchema(reservationServiceMethods.ByName("RemoveServiceFromProvider")),
			connect.WithClientOptions(opts...),
		),
		getProviderServicesList: connect.NewClient[reservations.GetProviderServicesListRequest, reservations.GetProviderServicesListResponse](
			httpClient,
			baseURL+ReservationServiceGetProviderServicesListProcedure,
			connect.WithSchema(reservationServiceMethods.ByName("GetProviderServicesList")),
			connect.WithClientOptions(opts...),
		),
		updateProviderService: connect.NewClient[reservations.UpdateProviderServiceRequest, reservations.UpdateProviderServiceResponse](
			httpClient,
			baseURL+ReservationServiceUpdateProviderServiceProcedure,
			connect.WithSchema(reservationServiceMethods.ByName("UpdateProviderService")),
			connect.WithClientOptions(opts...),
		),
		createWeeklySchedule: connect.NewClient[reservations.CreateWeeklyScheduleRequest, reservations.CreateWeeklyScheduleResponse](
			httpClient,
			baseURL+ReservationServiceCreateWeeklyScheduleProcedure,
			connect.WithSchema(reservationServiceMethods.ByName("CreateWeeklySchedule")),
			connect.WithClientOptions(opts...),
		),
		getWeeklyScheduleList: connect.NewClient[reservations.GetWeeklyScheduleListRequest, reservations.GetWeeklyScheduleListResponse](
			httpClient,
			baseURL+ReservationServiceGetWeeklyScheduleListProcedure,
			connect.WithSchema(reservationServiceMethods.ByName("GetWeeklyScheduleList")),
			connect.WithClientOptions(opts...),
		),
		updateWeeklySchedule: connect.NewClient[reservations.UpdateWeeklyScheduleRequest, reservations.UpdateWeeklyScheduleResponse](
			httpClient,
			baseURL+ReservationServiceUpdateWeeklyScheduleProcedure,
			connect.WithSchema(reservationServiceMethods.ByName("UpdateWeeklySchedule")),
			connect.WithClientOptions(opts...),
		),
		removeWeeklySchedule: connect.NewClient[reservations.RemoveWeeklyScheduleRequest, reservations.RemoveWeeklyScheduleResponse](
			httpClient,
			baseURL+ReservationServiceRemoveWeeklyScheduleProcedure,
			connect.WithSchema(reservationServiceMethods.ByName("RemoveWeeklySchedule")),
			connect.WithClientOptions(opts...),
		),
		generateTimeSlots: connect.NewClient[reservations.GenerateTimeSlotsRequest, reservations.GenerateTimeSlotsResponse](
			httpClient,
			baseURL+ReservationServiceGenerateTimeSlotsProcedure,
			connect.WithSchema(reservationServiceMethods.ByName("GenerateTimeSlots")),
			connect.WithClientOptions(opts...),
		),
		getTimeSlotsList: connect.NewClient[reservations.GetTimeSlotsListRequest, reservations.GetTimeSlotsListResponse](
			httpClient,
			baseURL+ReservationServiceGetTimeSlotsListProcedure,
			connect.WithSchema(reservationServiceMethods.ByName("GetTimeSlotsList")),
			connect.WithClientOptions(opts...),
		),
		updateTimeSlot: connect.NewClient[reservations.UpdateTimeSlotRequest, reservations.UpdateTimeSlotResponse](
			httpClient,
			baseURL+ReservationServiceUpdateTimeSlotProcedure,
			connect.WithSchema(reservationServiceMethods.ByName("UpdateTimeSlot")),
			connect.WithClientOptions(opts...),
		),
		removeTimeSlots: connect.NewClient[reservations.RemoveTimeSlotsRequest, reservations.RemoveTimeSlotsResponse](
			httpClient,
			baseURL+ReservationServiceRemoveTimeSlotsProcedure,
			connect.WithSchema(reservationServiceMethods.ByName("RemoveTimeSlots")),
			connect.WithClientOptions(opts...),
		),
		createReservation: connect.NewClient[reservations.CreateReservationRequest, reservations.CreateReservationResponse](
			httpClient,
			baseURL+ReservationServiceCreateReservationProcedure,
			connect.WithSchema(reservationServiceMethods.ByName("CreateReservation")),
			connect.WithClientOptions(opts...),
		),
		updateReservationStatus: connect.NewClient[reservations.UpdateReservationRequest, reservations.UpdateReservationResponse](
			httpClient,
			baseURL+ReservationServiceUpdateReservationStatusProcedure,
			connect.WithSchema(reservationServiceMethods.ByName("UpdateReservationStatus")),
			connect.WithClientOptions(opts...),
		),
		listReservations: connect.NewClient[reservations.ListReservationsRequest, reservations.ListReservationsResponse](
			httpClient,
			baseURL+ReservationServiceListReservationsProcedure,
			connect.WithSchema(reservationServiceMethods.ByName("ListReservations")),
			connect.WithClientOptions(opts...),
		),
		removeReservation: connect.NewClient[reservations.DeleteReservationRequest, reservations.DeleteReservationResponse](
			httpClient,
			baseURL+ReservationServiceRemoveReservationProcedure,
			connect.WithSchema(reservationServiceMethods.ByName("RemoveReservation")),
			connect.WithClientOptions(opts...),
		),
		createCustomer: connect.NewClient[reservations.CreateCustomerRequest, reservations.CreateCustomerResponse](
			httpClient,
			baseURL+ReservationServiceCreateCustomerProcedure,
			connect.WithSchema(reservationServiceMethods.ByName("CreateCustomer")),
			connect.WithClientOptions(opts...),
		),
		updateCustomer: connect.NewClient[reservations.UpdateCustomerRequest, reservations.UpdateCustomerResponse](
			httpClient,
			baseURL+ReservationServiceUpdateCustomerProcedure,
			connect.WithSchema(reservationServiceMethods.ByName("UpdateCustomer")),
			connect.WithClientOptions(opts...),
		),
		listCustomer: connect.NewClient[reservations.ListCustomerRequest, reservations.ListCustomerResponse](
			httpClient,
			baseURL+ReservationServiceListCustomerProcedure,
			connect.WithSchema(reservationServiceMethods.ByName("ListCustomer")),
			connect.WithClientOptions(opts...),
		),
		getProviderServicesWithUsers: connect.NewClient[reservations.GetProviderServicesWithUsersRequest, reservations.GetProviderServicesWithUsersResponse](
			httpClient,
			baseURL+ReservationServiceGetProviderServicesWithUsersProcedure,
			connect.WithSchema(reservationServiceMethods.ByName("GetProviderServicesWithUsers")),
			connect.WithClientOptions(opts...),
		),
		processAudio: connect.NewClient[reservations.ProcessAudioRequest, reservations.ProcessAudioResponse](
			httpClient,
			baseURL+ReservationServiceProcessAudioProcedure,
			connect.WithSchema(reservationServiceMethods.ByName("ProcessAudio")),
			connect.WithClientOptions(opts...),
		),
	}
}

// reservationServiceClient implements ReservationServiceClient.
type reservationServiceClient struct {
	createFacility               *connect.Client[reservations.CreateFacilityRequest, reservations.CreateFacilityResponse]
	updateFacility               *connect.Client[reservations.UpdateFacilityRequest, reservations.UpdateFacilityResponse]
	listFacilities               *connect.Client[reservations.ListFacilitiesRequest, reservations.ListFacilitiesResponse]
	createService                *connect.Client[reservations.CreateServiceRequest, reservations.CreateServiceResponse]
	updateService                *connect.Client[reservations.UpdateServiceRequest, reservations.UpdateServiceResponse]
	listServices                 *connect.Client[reservations.ListServicesRequest, reservations.ListServicesResponse]
	assignServiceToProvider      *connect.Client[reservations.AssignServiceToProviderRequest, reservations.AssignServiceToProviderResponse]
	removeServiceFromProvider    *connect.Client[reservations.RemoveServiceFromProviderRequest, reservations.RemoveServiceFromProviderResponse]
	getProviderServicesList      *connect.Client[reservations.GetProviderServicesListRequest, reservations.GetProviderServicesListResponse]
	updateProviderService        *connect.Client[reservations.UpdateProviderServiceRequest, reservations.UpdateProviderServiceResponse]
	createWeeklySchedule         *connect.Client[reservations.CreateWeeklyScheduleRequest, reservations.CreateWeeklyScheduleResponse]
	getWeeklyScheduleList        *connect.Client[reservations.GetWeeklyScheduleListRequest, reservations.GetWeeklyScheduleListResponse]
	updateWeeklySchedule         *connect.Client[reservations.UpdateWeeklyScheduleRequest, reservations.UpdateWeeklyScheduleResponse]
	removeWeeklySchedule         *connect.Client[reservations.RemoveWeeklyScheduleRequest, reservations.RemoveWeeklyScheduleResponse]
	generateTimeSlots            *connect.Client[reservations.GenerateTimeSlotsRequest, reservations.GenerateTimeSlotsResponse]
	getTimeSlotsList             *connect.Client[reservations.GetTimeSlotsListRequest, reservations.GetTimeSlotsListResponse]
	updateTimeSlot               *connect.Client[reservations.UpdateTimeSlotRequest, reservations.UpdateTimeSlotResponse]
	removeTimeSlots              *connect.Client[reservations.RemoveTimeSlotsRequest, reservations.RemoveTimeSlotsResponse]
	createReservation            *connect.Client[reservations.CreateReservationRequest, reservations.CreateReservationResponse]
	updateReservationStatus      *connect.Client[reservations.UpdateReservationRequest, reservations.UpdateReservationResponse]
	listReservations             *connect.Client[reservations.ListReservationsRequest, reservations.ListReservationsResponse]
	removeReservation            *connect.Client[reservations.DeleteReservationRequest, reservations.DeleteReservationResponse]
	createCustomer               *connect.Client[reservations.CreateCustomerRequest, reservations.CreateCustomerResponse]
	updateCustomer               *connect.Client[reservations.UpdateCustomerRequest, reservations.UpdateCustomerResponse]
	listCustomer                 *connect.Client[reservations.ListCustomerRequest, reservations.ListCustomerResponse]
	getProviderServicesWithUsers *connect.Client[reservations.GetProviderServicesWithUsersRequest, reservations.GetProviderServicesWithUsersResponse]
	processAudio                 *connect.Client[reservations.ProcessAudioRequest, reservations.ProcessAudioResponse]
}

// CreateFacility calls reservation.ReservationService.CreateFacility.
func (c *reservationServiceClient) CreateFacility(ctx context.Context, req *connect.Request[reservations.CreateFacilityRequest]) (*connect.Response[reservations.CreateFacilityResponse], error) {
	return c.createFacility.CallUnary(ctx, req)
}

// UpdateFacility calls reservation.ReservationService.UpdateFacility.
func (c *reservationServiceClient) UpdateFacility(ctx context.Context, req *connect.Request[reservations.UpdateFacilityRequest]) (*connect.Response[reservations.UpdateFacilityResponse], error) {
	return c.updateFacility.CallUnary(ctx, req)
}

// ListFacilities calls reservation.ReservationService.ListFacilities.
func (c *reservationServiceClient) ListFacilities(ctx context.Context, req *connect.Request[reservations.ListFacilitiesRequest]) (*connect.Response[reservations.ListFacilitiesResponse], error) {
	return c.listFacilities.CallUnary(ctx, req)
}

// CreateService calls reservation.ReservationService.CreateService.
func (c *reservationServiceClient) CreateService(ctx context.Context, req *connect.Request[reservations.CreateServiceRequest]) (*connect.Response[reservations.CreateServiceResponse], error) {
	return c.createService.CallUnary(ctx, req)
}

// UpdateService calls reservation.ReservationService.UpdateService.
func (c *reservationServiceClient) UpdateService(ctx context.Context, req *connect.Request[reservations.UpdateServiceRequest]) (*connect.Response[reservations.UpdateServiceResponse], error) {
	return c.updateService.CallUnary(ctx, req)
}

// ListServices calls reservation.ReservationService.ListServices.
func (c *reservationServiceClient) ListServices(ctx context.Context, req *connect.Request[reservations.ListServicesRequest]) (*connect.Response[reservations.ListServicesResponse], error) {
	return c.listServices.CallUnary(ctx, req)
}

// AssignServiceToProvider calls reservation.ReservationService.AssignServiceToProvider.
func (c *reservationServiceClient) AssignServiceToProvider(ctx context.Context, req *connect.Request[reservations.AssignServiceToProviderRequest]) (*connect.Response[reservations.AssignServiceToProviderResponse], error) {
	return c.assignServiceToProvider.CallUnary(ctx, req)
}

// RemoveServiceFromProvider calls reservation.ReservationService.RemoveServiceFromProvider.
func (c *reservationServiceClient) RemoveServiceFromProvider(ctx context.Context, req *connect.Request[reservations.RemoveServiceFromProviderRequest]) (*connect.Response[reservations.RemoveServiceFromProviderResponse], error) {
	return c.removeServiceFromProvider.CallUnary(ctx, req)
}

// GetProviderServicesList calls reservation.ReservationService.GetProviderServicesList.
func (c *reservationServiceClient) GetProviderServicesList(ctx context.Context, req *connect.Request[reservations.GetProviderServicesListRequest]) (*connect.Response[reservations.GetProviderServicesListResponse], error) {
	return c.getProviderServicesList.CallUnary(ctx, req)
}

// UpdateProviderService calls reservation.ReservationService.UpdateProviderService.
func (c *reservationServiceClient) UpdateProviderService(ctx context.Context, req *connect.Request[reservations.UpdateProviderServiceRequest]) (*connect.Response[reservations.UpdateProviderServiceResponse], error) {
	return c.updateProviderService.CallUnary(ctx, req)
}

// CreateWeeklySchedule calls reservation.ReservationService.CreateWeeklySchedule.
func (c *reservationServiceClient) CreateWeeklySchedule(ctx context.Context, req *connect.Request[reservations.CreateWeeklyScheduleRequest]) (*connect.Response[reservations.CreateWeeklyScheduleResponse], error) {
	return c.createWeeklySchedule.CallUnary(ctx, req)
}

// GetWeeklyScheduleList calls reservation.ReservationService.GetWeeklyScheduleList.
func (c *reservationServiceClient) GetWeeklyScheduleList(ctx context.Context, req *connect.Request[reservations.GetWeeklyScheduleListRequest]) (*connect.Response[reservations.GetWeeklyScheduleListResponse], error) {
	return c.getWeeklyScheduleList.CallUnary(ctx, req)
}

// UpdateWeeklySchedule calls reservation.ReservationService.UpdateWeeklySchedule.
func (c *reservationServiceClient) UpdateWeeklySchedule(ctx context.Context, req *connect.Request[reservations.UpdateWeeklyScheduleRequest]) (*connect.Response[reservations.UpdateWeeklyScheduleResponse], error) {
	return c.updateWeeklySchedule.CallUnary(ctx, req)
}

// RemoveWeeklySchedule calls reservation.ReservationService.RemoveWeeklySchedule.
func (c *reservationServiceClient) RemoveWeeklySchedule(ctx context.Context, req *connect.Request[reservations.RemoveWeeklyScheduleRequest]) (*connect.Response[reservations.RemoveWeeklyScheduleResponse], error) {
	return c.removeWeeklySchedule.CallUnary(ctx, req)
}

// GenerateTimeSlots calls reservation.ReservationService.GenerateTimeSlots.
func (c *reservationServiceClient) GenerateTimeSlots(ctx context.Context, req *connect.Request[reservations.GenerateTimeSlotsRequest]) (*connect.Response[reservations.GenerateTimeSlotsResponse], error) {
	return c.generateTimeSlots.CallUnary(ctx, req)
}

// GetTimeSlotsList calls reservation.ReservationService.GetTimeSlotsList.
func (c *reservationServiceClient) GetTimeSlotsList(ctx context.Context, req *connect.Request[reservations.GetTimeSlotsListRequest]) (*connect.Response[reservations.GetTimeSlotsListResponse], error) {
	return c.getTimeSlotsList.CallUnary(ctx, req)
}

// UpdateTimeSlot calls reservation.ReservationService.UpdateTimeSlot.
func (c *reservationServiceClient) UpdateTimeSlot(ctx context.Context, req *connect.Request[reservations.UpdateTimeSlotRequest]) (*connect.Response[reservations.UpdateTimeSlotResponse], error) {
	return c.updateTimeSlot.CallUnary(ctx, req)
}

// RemoveTimeSlots calls reservation.ReservationService.RemoveTimeSlots.
func (c *reservationServiceClient) RemoveTimeSlots(ctx context.Context, req *connect.Request[reservations.RemoveTimeSlotsRequest]) (*connect.Response[reservations.RemoveTimeSlotsResponse], error) {
	return c.removeTimeSlots.CallUnary(ctx, req)
}

// CreateReservation calls reservation.ReservationService.CreateReservation.
func (c *reservationServiceClient) CreateReservation(ctx context.Context, req *connect.Request[reservations.CreateReservationRequest]) (*connect.Response[reservations.CreateReservationResponse], error) {
	return c.createReservation.CallUnary(ctx, req)
}

// UpdateReservationStatus calls reservation.ReservationService.UpdateReservationStatus.
func (c *reservationServiceClient) UpdateReservationStatus(ctx context.Context, req *connect.Request[reservations.UpdateReservationRequest]) (*connect.Response[reservations.UpdateReservationResponse], error) {
	return c.updateReservationStatus.CallUnary(ctx, req)
}

// ListReservations calls reservation.ReservationService.ListReservations.
func (c *reservationServiceClient) ListReservations(ctx context.Context, req *connect.Request[reservations.ListReservationsRequest]) (*connect.Response[reservations.ListReservationsResponse], error) {
	return c.listReservations.CallUnary(ctx, req)
}

// RemoveReservation calls reservation.ReservationService.RemoveReservation.
func (c *reservationServiceClient) RemoveReservation(ctx context.Context, req *connect.Request[reservations.DeleteReservationRequest]) (*connect.Response[reservations.DeleteReservationResponse], error) {
	return c.removeReservation.CallUnary(ctx, req)
}

// CreateCustomer calls reservation.ReservationService.CreateCustomer.
func (c *reservationServiceClient) CreateCustomer(ctx context.Context, req *connect.Request[reservations.CreateCustomerRequest]) (*connect.Response[reservations.CreateCustomerResponse], error) {
	return c.createCustomer.CallUnary(ctx, req)
}

// UpdateCustomer calls reservation.ReservationService.UpdateCustomer.
func (c *reservationServiceClient) UpdateCustomer(ctx context.Context, req *connect.Request[reservations.UpdateCustomerRequest]) (*connect.Response[reservations.UpdateCustomerResponse], error) {
	return c.updateCustomer.CallUnary(ctx, req)
}

// ListCustomer calls reservation.ReservationService.ListCustomer.
func (c *reservationServiceClient) ListCustomer(ctx context.Context, req *connect.Request[reservations.ListCustomerRequest]) (*connect.Response[reservations.ListCustomerResponse], error) {
	return c.listCustomer.CallUnary(ctx, req)
}

// GetProviderServicesWithUsers calls reservation.ReservationService.GetProviderServicesWithUsers.
func (c *reservationServiceClient) GetProviderServicesWithUsers(ctx context.Context, req *connect.Request[reservations.GetProviderServicesWithUsersRequest]) (*connect.Response[reservations.GetProviderServicesWithUsersResponse], error) {
	return c.getProviderServicesWithUsers.CallUnary(ctx, req)
}

// ProcessAudio calls reservation.ReservationService.ProcessAudio.
func (c *reservationServiceClient) ProcessAudio(ctx context.Context, req *connect.Request[reservations.ProcessAudioRequest]) (*connect.Response[reservations.ProcessAudioResponse], error) {
	return c.processAudio.CallUnary(ctx, req)
}

// ReservationServiceHandler is an implementation of the reservation.ReservationService service.
type ReservationServiceHandler interface {
	// facility related methods
	// ایجاد یک فسیلیتی جدید | Create a new facility
	CreateFacility(context.Context, *connect.Request[reservations.CreateFacilityRequest]) (*connect.Response[reservations.CreateFacilityResponse], error)
	// ویرایش یم فسیلیتی| update a  facility
	UpdateFacility(context.Context, *connect.Request[reservations.UpdateFacilityRequest]) (*connect.Response[reservations.UpdateFacilityResponse], error)
	// دریافت لیست مکان‌ها | List all facilities
	ListFacilities(context.Context, *connect.Request[reservations.ListFacilitiesRequest]) (*connect.Response[reservations.ListFacilitiesResponse], error)
	// Service related methods
	// ایجاد سرویس جدید برای یک فسیلیتی | Create a new service for a facility
	CreateService(context.Context, *connect.Request[reservations.CreateServiceRequest]) (*connect.Response[reservations.CreateServiceResponse], error)
	// ویرایش سرویس  | Update a service for a facility
	UpdateService(context.Context, *connect.Request[reservations.UpdateServiceRequest]) (*connect.Response[reservations.UpdateServiceResponse], error)
	// دریافت لیست سرویس‌های یک فسیلیتی | List services of a facility
	ListServices(context.Context, *connect.Request[reservations.ListServicesRequest]) (*connect.Response[reservations.ListServicesResponse], error)
	// ُProvider Service  related methods
	// تخصیص یک سرویس به ارائه‌دهنده | Assign a service to a provider
	AssignServiceToProvider(context.Context, *connect.Request[reservations.AssignServiceToProviderRequest]) (*connect.Response[reservations.AssignServiceToProviderResponse], error)
	// خذف یک سرویس از ارائه‌دهنده | Remove a service from a provider
	RemoveServiceFromProvider(context.Context, *connect.Request[reservations.RemoveServiceFromProviderRequest]) (*connect.Response[reservations.RemoveServiceFromProviderResponse], error)
	// دریافت لیست سرویس‌های یک ارائه‌دهنده| Get provider services
	GetProviderServicesList(context.Context, *connect.Request[reservations.GetProviderServicesListRequest]) (*connect.Response[reservations.GetProviderServicesListResponse], error)
	// ویرایش سرویس  | Update a service for a provider
	UpdateProviderService(context.Context, *connect.Request[reservations.UpdateProviderServiceRequest]) (*connect.Response[reservations.UpdateProviderServiceResponse], error)
	// WeeklySchedule and TimeSlot releated methods
	// ایجاد برنامه‌ زمانی هفتگی برای ارائه‌دهنده | Create weekly schedule for provider
	CreateWeeklySchedule(context.Context, *connect.Request[reservations.CreateWeeklyScheduleRequest]) (*connect.Response[reservations.CreateWeeklyScheduleResponse], error)
	GetWeeklyScheduleList(context.Context, *connect.Request[reservations.GetWeeklyScheduleListRequest]) (*connect.Response[reservations.GetWeeklyScheduleListResponse], error)
	UpdateWeeklySchedule(context.Context, *connect.Request[reservations.UpdateWeeklyScheduleRequest]) (*connect.Response[reservations.UpdateWeeklyScheduleResponse], error)
	RemoveWeeklySchedule(context.Context, *connect.Request[reservations.RemoveWeeklyScheduleRequest]) (*connect.Response[reservations.RemoveWeeklyScheduleResponse], error)
	// تولید تایم‌اسلات‌ها بر اساس برنامه‌ هفتگی | Generate time slots from weekly schedule
	GenerateTimeSlots(context.Context, *connect.Request[reservations.GenerateTimeSlotsRequest]) (*connect.Response[reservations.GenerateTimeSlotsResponse], error)
	GetTimeSlotsList(context.Context, *connect.Request[reservations.GetTimeSlotsListRequest]) (*connect.Response[reservations.GetTimeSlotsListResponse], error)
	UpdateTimeSlot(context.Context, *connect.Request[reservations.UpdateTimeSlotRequest]) (*connect.Response[reservations.UpdateTimeSlotResponse], error)
	RemoveTimeSlots(context.Context, *connect.Request[reservations.RemoveTimeSlotsRequest]) (*connect.Response[reservations.RemoveTimeSlotsResponse], error)
	// 🔹  رزرو | Reservation
	CreateReservation(context.Context, *connect.Request[reservations.CreateReservationRequest]) (*connect.Response[reservations.CreateReservationResponse], error)
	UpdateReservationStatus(context.Context, *connect.Request[reservations.UpdateReservationRequest]) (*connect.Response[reservations.UpdateReservationResponse], error)
	ListReservations(context.Context, *connect.Request[reservations.ListReservationsRequest]) (*connect.Response[reservations.ListReservationsResponse], error)
	RemoveReservation(context.Context, *connect.Request[reservations.DeleteReservationRequest]) (*connect.Response[reservations.DeleteReservationResponse], error)
	// 🔹  Customer
	CreateCustomer(context.Context, *connect.Request[reservations.CreateCustomerRequest]) (*connect.Response[reservations.CreateCustomerResponse], error)
	UpdateCustomer(context.Context, *connect.Request[reservations.UpdateCustomerRequest]) (*connect.Response[reservations.UpdateCustomerResponse], error)
	ListCustomer(context.Context, *connect.Request[reservations.ListCustomerRequest]) (*connect.Response[reservations.ListCustomerResponse], error)
	// DOT
	GetProviderServicesWithUsers(context.Context, *connect.Request[reservations.GetProviderServicesWithUsersRequest]) (*connect.Response[reservations.GetProviderServicesWithUsersResponse], error)
	// پردازش یک فایل صوتی و برگرداندن متن و فیلترها
	// برای شروع ساده: درخواست تک با بایت‌های فایل (مناسب برای فایلی تا چندین مگ)
	ProcessAudio(context.Context, *connect.Request[reservations.ProcessAudioRequest]) (*connect.Response[reservations.ProcessAudioResponse], error)
}

// NewReservationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewReservationServiceHandler(svc ReservationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	reservationServiceMethods := reservations.File_reservations_reservation_proto.Services().ByName("ReservationService").Methods()
	reservationServiceCreateFacilityHandler := connect.NewUnaryHandler(
		ReservationServiceCreateFacilityProcedure,
		svc.CreateFacility,
		connect.WithSchema(reservationServiceMethods.ByName("CreateFacility")),
		connect.WithHandlerOptions(opts...),
	)
	reservationServiceUpdateFacilityHandler := connect.NewUnaryHandler(
		ReservationServiceUpdateFacilityProcedure,
		svc.UpdateFacility,
		connect.WithSchema(reservationServiceMethods.ByName("UpdateFacility")),
		connect.WithHandlerOptions(opts...),
	)
	reservationServiceListFacilitiesHandler := connect.NewUnaryHandler(
		ReservationServiceListFacilitiesProcedure,
		svc.ListFacilities,
		connect.WithSchema(reservationServiceMethods.ByName("ListFacilities")),
		connect.WithHandlerOptions(opts...),
	)
	reservationServiceCreateServiceHandler := connect.NewUnaryHandler(
		ReservationServiceCreateServiceProcedure,
		svc.CreateService,
		connect.WithSchema(reservationServiceMethods.ByName("CreateService")),
		connect.WithHandlerOptions(opts...),
	)
	reservationServiceUpdateServiceHandler := connect.NewUnaryHandler(
		ReservationServiceUpdateServiceProcedure,
		svc.UpdateService,
		connect.WithSchema(reservationServiceMethods.ByName("UpdateService")),
		connect.WithHandlerOptions(opts...),
	)
	reservationServiceListServicesHandler := connect.NewUnaryHandler(
		ReservationServiceListServicesProcedure,
		svc.ListServices,
		connect.WithSchema(reservationServiceMethods.ByName("ListServices")),
		connect.WithHandlerOptions(opts...),
	)
	reservationServiceAssignServiceToProviderHandler := connect.NewUnaryHandler(
		ReservationServiceAssignServiceToProviderProcedure,
		svc.AssignServiceToProvider,
		connect.WithSchema(reservationServiceMethods.ByName("AssignServiceToProvider")),
		connect.WithHandlerOptions(opts...),
	)
	reservationServiceRemoveServiceFromProviderHandler := connect.NewUnaryHandler(
		ReservationServiceRemoveServiceFromProviderProcedure,
		svc.RemoveServiceFromProvider,
		connect.WithSchema(reservationServiceMethods.ByName("RemoveServiceFromProvider")),
		connect.WithHandlerOptions(opts...),
	)
	reservationServiceGetProviderServicesListHandler := connect.NewUnaryHandler(
		ReservationServiceGetProviderServicesListProcedure,
		svc.GetProviderServicesList,
		connect.WithSchema(reservationServiceMethods.ByName("GetProviderServicesList")),
		connect.WithHandlerOptions(opts...),
	)
	reservationServiceUpdateProviderServiceHandler := connect.NewUnaryHandler(
		ReservationServiceUpdateProviderServiceProcedure,
		svc.UpdateProviderService,
		connect.WithSchema(reservationServiceMethods.ByName("UpdateProviderService")),
		connect.WithHandlerOptions(opts...),
	)
	reservationServiceCreateWeeklyScheduleHandler := connect.NewUnaryHandler(
		ReservationServiceCreateWeeklyScheduleProcedure,
		svc.CreateWeeklySchedule,
		connect.WithSchema(reservationServiceMethods.ByName("CreateWeeklySchedule")),
		connect.WithHandlerOptions(opts...),
	)
	reservationServiceGetWeeklyScheduleListHandler := connect.NewUnaryHandler(
		ReservationServiceGetWeeklyScheduleListProcedure,
		svc.GetWeeklyScheduleList,
		connect.WithSchema(reservationServiceMethods.ByName("GetWeeklyScheduleList")),
		connect.WithHandlerOptions(opts...),
	)
	reservationServiceUpdateWeeklyScheduleHandler := connect.NewUnaryHandler(
		ReservationServiceUpdateWeeklyScheduleProcedure,
		svc.UpdateWeeklySchedule,
		connect.WithSchema(reservationServiceMethods.ByName("UpdateWeeklySchedule")),
		connect.WithHandlerOptions(opts...),
	)
	reservationServiceRemoveWeeklyScheduleHandler := connect.NewUnaryHandler(
		ReservationServiceRemoveWeeklyScheduleProcedure,
		svc.RemoveWeeklySchedule,
		connect.WithSchema(reservationServiceMethods.ByName("RemoveWeeklySchedule")),
		connect.WithHandlerOptions(opts...),
	)
	reservationServiceGenerateTimeSlotsHandler := connect.NewUnaryHandler(
		ReservationServiceGenerateTimeSlotsProcedure,
		svc.GenerateTimeSlots,
		connect.WithSchema(reservationServiceMethods.ByName("GenerateTimeSlots")),
		connect.WithHandlerOptions(opts...),
	)
	reservationServiceGetTimeSlotsListHandler := connect.NewUnaryHandler(
		ReservationServiceGetTimeSlotsListProcedure,
		svc.GetTimeSlotsList,
		connect.WithSchema(reservationServiceMethods.ByName("GetTimeSlotsList")),
		connect.WithHandlerOptions(opts...),
	)
	reservationServiceUpdateTimeSlotHandler := connect.NewUnaryHandler(
		ReservationServiceUpdateTimeSlotProcedure,
		svc.UpdateTimeSlot,
		connect.WithSchema(reservationServiceMethods.ByName("UpdateTimeSlot")),
		connect.WithHandlerOptions(opts...),
	)
	reservationServiceRemoveTimeSlotsHandler := connect.NewUnaryHandler(
		ReservationServiceRemoveTimeSlotsProcedure,
		svc.RemoveTimeSlots,
		connect.WithSchema(reservationServiceMethods.ByName("RemoveTimeSlots")),
		connect.WithHandlerOptions(opts...),
	)
	reservationServiceCreateReservationHandler := connect.NewUnaryHandler(
		ReservationServiceCreateReservationProcedure,
		svc.CreateReservation,
		connect.WithSchema(reservationServiceMethods.ByName("CreateReservation")),
		connect.WithHandlerOptions(opts...),
	)
	reservationServiceUpdateReservationStatusHandler := connect.NewUnaryHandler(
		ReservationServiceUpdateReservationStatusProcedure,
		svc.UpdateReservationStatus,
		connect.WithSchema(reservationServiceMethods.ByName("UpdateReservationStatus")),
		connect.WithHandlerOptions(opts...),
	)
	reservationServiceListReservationsHandler := connect.NewUnaryHandler(
		ReservationServiceListReservationsProcedure,
		svc.ListReservations,
		connect.WithSchema(reservationServiceMethods.ByName("ListReservations")),
		connect.WithHandlerOptions(opts...),
	)
	reservationServiceRemoveReservationHandler := connect.NewUnaryHandler(
		ReservationServiceRemoveReservationProcedure,
		svc.RemoveReservation,
		connect.WithSchema(reservationServiceMethods.ByName("RemoveReservation")),
		connect.WithHandlerOptions(opts...),
	)
	reservationServiceCreateCustomerHandler := connect.NewUnaryHandler(
		ReservationServiceCreateCustomerProcedure,
		svc.CreateCustomer,
		connect.WithSchema(reservationServiceMethods.ByName("CreateCustomer")),
		connect.WithHandlerOptions(opts...),
	)
	reservationServiceUpdateCustomerHandler := connect.NewUnaryHandler(
		ReservationServiceUpdateCustomerProcedure,
		svc.UpdateCustomer,
		connect.WithSchema(reservationServiceMethods.ByName("UpdateCustomer")),
		connect.WithHandlerOptions(opts...),
	)
	reservationServiceListCustomerHandler := connect.NewUnaryHandler(
		ReservationServiceListCustomerProcedure,
		svc.ListCustomer,
		connect.WithSchema(reservationServiceMethods.ByName("ListCustomer")),
		connect.WithHandlerOptions(opts...),
	)
	reservationServiceGetProviderServicesWithUsersHandler := connect.NewUnaryHandler(
		ReservationServiceGetProviderServicesWithUsersProcedure,
		svc.GetProviderServicesWithUsers,
		connect.WithSchema(reservationServiceMethods.ByName("GetProviderServicesWithUsers")),
		connect.WithHandlerOptions(opts...),
	)
	reservationServiceProcessAudioHandler := connect.NewUnaryHandler(
		ReservationServiceProcessAudioProcedure,
		svc.ProcessAudio,
		connect.WithSchema(reservationServiceMethods.ByName("ProcessAudio")),
		connect.WithHandlerOptions(opts...),
	)
	return "/reservation.ReservationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ReservationServiceCreateFacilityProcedure:
			reservationServiceCreateFacilityHandler.ServeHTTP(w, r)
		case ReservationServiceUpdateFacilityProcedure:
			reservationServiceUpdateFacilityHandler.ServeHTTP(w, r)
		case ReservationServiceListFacilitiesProcedure:
			reservationServiceListFacilitiesHandler.ServeHTTP(w, r)
		case ReservationServiceCreateServiceProcedure:
			reservationServiceCreateServiceHandler.ServeHTTP(w, r)
		case ReservationServiceUpdateServiceProcedure:
			reservationServiceUpdateServiceHandler.ServeHTTP(w, r)
		case ReservationServiceListServicesProcedure:
			reservationServiceListServicesHandler.ServeHTTP(w, r)
		case ReservationServiceAssignServiceToProviderProcedure:
			reservationServiceAssignServiceToProviderHandler.ServeHTTP(w, r)
		case ReservationServiceRemoveServiceFromProviderProcedure:
			reservationServiceRemoveServiceFromProviderHandler.ServeHTTP(w, r)
		case ReservationServiceGetProviderServicesListProcedure:
			reservationServiceGetProviderServicesListHandler.ServeHTTP(w, r)
		case ReservationServiceUpdateProviderServiceProcedure:
			reservationServiceUpdateProviderServiceHandler.ServeHTTP(w, r)
		case ReservationServiceCreateWeeklyScheduleProcedure:
			reservationServiceCreateWeeklyScheduleHandler.ServeHTTP(w, r)
		case ReservationServiceGetWeeklyScheduleListProcedure:
			reservationServiceGetWeeklyScheduleListHandler.ServeHTTP(w, r)
		case ReservationServiceUpdateWeeklyScheduleProcedure:
			reservationServiceUpdateWeeklyScheduleHandler.ServeHTTP(w, r)
		case ReservationServiceRemoveWeeklyScheduleProcedure:
			reservationServiceRemoveWeeklyScheduleHandler.ServeHTTP(w, r)
		case ReservationServiceGenerateTimeSlotsProcedure:
			reservationServiceGenerateTimeSlotsHandler.ServeHTTP(w, r)
		case ReservationServiceGetTimeSlotsListProcedure:
			reservationServiceGetTimeSlotsListHandler.ServeHTTP(w, r)
		case ReservationServiceUpdateTimeSlotProcedure:
			reservationServiceUpdateTimeSlotHandler.ServeHTTP(w, r)
		case ReservationServiceRemoveTimeSlotsProcedure:
			reservationServiceRemoveTimeSlotsHandler.ServeHTTP(w, r)
		case ReservationServiceCreateReservationProcedure:
			reservationServiceCreateReservationHandler.ServeHTTP(w, r)
		case ReservationServiceUpdateReservationStatusProcedure:
			reservationServiceUpdateReservationStatusHandler.ServeHTTP(w, r)
		case ReservationServiceListReservationsProcedure:
			reservationServiceListReservationsHandler.ServeHTTP(w, r)
		case ReservationServiceRemoveReservationProcedure:
			reservationServiceRemoveReservationHandler.ServeHTTP(w, r)
		case ReservationServiceCreateCustomerProcedure:
			reservationServiceCreateCustomerHandler.ServeHTTP(w, r)
		case ReservationServiceUpdateCustomerProcedure:
			reservationServiceUpdateCustomerHandler.ServeHTTP(w, r)
		case ReservationServiceListCustomerProcedure:
			reservationServiceListCustomerHandler.ServeHTTP(w, r)
		case ReservationServiceGetProviderServicesWithUsersProcedure:
			reservationServiceGetProviderServicesWithUsersHandler.ServeHTTP(w, r)
		case ReservationServiceProcessAudioProcedure:
			reservationServiceProcessAudioHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedReservationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedReservationServiceHandler struct{}

func (UnimplementedReservationServiceHandler) CreateFacility(context.Context, *connect.Request[reservations.CreateFacilityRequest]) (*connect.Response[reservations.CreateFacilityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reservation.ReservationService.CreateFacility is not implemented"))
}

func (UnimplementedReservationServiceHandler) UpdateFacility(context.Context, *connect.Request[reservations.UpdateFacilityRequest]) (*connect.Response[reservations.UpdateFacilityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reservation.ReservationService.UpdateFacility is not implemented"))
}

func (UnimplementedReservationServiceHandler) ListFacilities(context.Context, *connect.Request[reservations.ListFacilitiesRequest]) (*connect.Response[reservations.ListFacilitiesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reservation.ReservationService.ListFacilities is not implemented"))
}

func (UnimplementedReservationServiceHandler) CreateService(context.Context, *connect.Request[reservations.CreateServiceRequest]) (*connect.Response[reservations.CreateServiceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reservation.ReservationService.CreateService is not implemented"))
}

func (UnimplementedReservationServiceHandler) UpdateService(context.Context, *connect.Request[reservations.UpdateServiceRequest]) (*connect.Response[reservations.UpdateServiceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reservation.ReservationService.UpdateService is not implemented"))
}

func (UnimplementedReservationServiceHandler) ListServices(context.Context, *connect.Request[reservations.ListServicesRequest]) (*connect.Response[reservations.ListServicesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reservation.ReservationService.ListServices is not implemented"))
}

func (UnimplementedReservationServiceHandler) AssignServiceToProvider(context.Context, *connect.Request[reservations.AssignServiceToProviderRequest]) (*connect.Response[reservations.AssignServiceToProviderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reservation.ReservationService.AssignServiceToProvider is not implemented"))
}

func (UnimplementedReservationServiceHandler) RemoveServiceFromProvider(context.Context, *connect.Request[reservations.RemoveServiceFromProviderRequest]) (*connect.Response[reservations.RemoveServiceFromProviderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reservation.ReservationService.RemoveServiceFromProvider is not implemented"))
}

func (UnimplementedReservationServiceHandler) GetProviderServicesList(context.Context, *connect.Request[reservations.GetProviderServicesListRequest]) (*connect.Response[reservations.GetProviderServicesListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reservation.ReservationService.GetProviderServicesList is not implemented"))
}

func (UnimplementedReservationServiceHandler) UpdateProviderService(context.Context, *connect.Request[reservations.UpdateProviderServiceRequest]) (*connect.Response[reservations.UpdateProviderServiceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reservation.ReservationService.UpdateProviderService is not implemented"))
}

func (UnimplementedReservationServiceHandler) CreateWeeklySchedule(context.Context, *connect.Request[reservations.CreateWeeklyScheduleRequest]) (*connect.Response[reservations.CreateWeeklyScheduleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reservation.ReservationService.CreateWeeklySchedule is not implemented"))
}

func (UnimplementedReservationServiceHandler) GetWeeklyScheduleList(context.Context, *connect.Request[reservations.GetWeeklyScheduleListRequest]) (*connect.Response[reservations.GetWeeklyScheduleListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reservation.ReservationService.GetWeeklyScheduleList is not implemented"))
}

func (UnimplementedReservationServiceHandler) UpdateWeeklySchedule(context.Context, *connect.Request[reservations.UpdateWeeklyScheduleRequest]) (*connect.Response[reservations.UpdateWeeklyScheduleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reservation.ReservationService.UpdateWeeklySchedule is not implemented"))
}

func (UnimplementedReservationServiceHandler) RemoveWeeklySchedule(context.Context, *connect.Request[reservations.RemoveWeeklyScheduleRequest]) (*connect.Response[reservations.RemoveWeeklyScheduleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reservation.ReservationService.RemoveWeeklySchedule is not implemented"))
}

func (UnimplementedReservationServiceHandler) GenerateTimeSlots(context.Context, *connect.Request[reservations.GenerateTimeSlotsRequest]) (*connect.Response[reservations.GenerateTimeSlotsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reservation.ReservationService.GenerateTimeSlots is not implemented"))
}

func (UnimplementedReservationServiceHandler) GetTimeSlotsList(context.Context, *connect.Request[reservations.GetTimeSlotsListRequest]) (*connect.Response[reservations.GetTimeSlotsListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reservation.ReservationService.GetTimeSlotsList is not implemented"))
}

func (UnimplementedReservationServiceHandler) UpdateTimeSlot(context.Context, *connect.Request[reservations.UpdateTimeSlotRequest]) (*connect.Response[reservations.UpdateTimeSlotResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reservation.ReservationService.UpdateTimeSlot is not implemented"))
}

func (UnimplementedReservationServiceHandler) RemoveTimeSlots(context.Context, *connect.Request[reservations.RemoveTimeSlotsRequest]) (*connect.Response[reservations.RemoveTimeSlotsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reservation.ReservationService.RemoveTimeSlots is not implemented"))
}

func (UnimplementedReservationServiceHandler) CreateReservation(context.Context, *connect.Request[reservations.CreateReservationRequest]) (*connect.Response[reservations.CreateReservationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reservation.ReservationService.CreateReservation is not implemented"))
}

func (UnimplementedReservationServiceHandler) UpdateReservationStatus(context.Context, *connect.Request[reservations.UpdateReservationRequest]) (*connect.Response[reservations.UpdateReservationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reservation.ReservationService.UpdateReservationStatus is not implemented"))
}

func (UnimplementedReservationServiceHandler) ListReservations(context.Context, *connect.Request[reservations.ListReservationsRequest]) (*connect.Response[reservations.ListReservationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reservation.ReservationService.ListReservations is not implemented"))
}

func (UnimplementedReservationServiceHandler) RemoveReservation(context.Context, *connect.Request[reservations.DeleteReservationRequest]) (*connect.Response[reservations.DeleteReservationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reservation.ReservationService.RemoveReservation is not implemented"))
}

func (UnimplementedReservationServiceHandler) CreateCustomer(context.Context, *connect.Request[reservations.CreateCustomerRequest]) (*connect.Response[reservations.CreateCustomerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reservation.ReservationService.CreateCustomer is not implemented"))
}

func (UnimplementedReservationServiceHandler) UpdateCustomer(context.Context, *connect.Request[reservations.UpdateCustomerRequest]) (*connect.Response[reservations.UpdateCustomerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reservation.ReservationService.UpdateCustomer is not implemented"))
}

func (UnimplementedReservationServiceHandler) ListCustomer(context.Context, *connect.Request[reservations.ListCustomerRequest]) (*connect.Response[reservations.ListCustomerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reservation.ReservationService.ListCustomer is not implemented"))
}

func (UnimplementedReservationServiceHandler) GetProviderServicesWithUsers(context.Context, *connect.Request[reservations.GetProviderServicesWithUsersRequest]) (*connect.Response[reservations.GetProviderServicesWithUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reservation.ReservationService.GetProviderServicesWithUsers is not implemented"))
}

func (UnimplementedReservationServiceHandler) ProcessAudio(context.Context, *connect.Request[reservations.ProcessAudioRequest]) (*connect.Response[reservations.ProcessAudioResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("reservation.ReservationService.ProcessAudio is not implemented"))
}
