// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: sessions/session.proto

package sessionsconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	sessions "github.com/az58740/connect-microservices-proto/golang/sessions"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SessionServiceName is the fully-qualified name of the SessionService service.
	SessionServiceName = "session.SessionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SessionServiceCreateSessionProcedure is the fully-qualified name of the SessionService's
	// CreateSession RPC.
	SessionServiceCreateSessionProcedure = "/session.SessionService/CreateSession"
	// SessionServiceUpdateSessionProcedure is the fully-qualified name of the SessionService's
	// UpdateSession RPC.
	SessionServiceUpdateSessionProcedure = "/session.SessionService/UpdateSession"
	// SessionServiceDeleteSessionProcedure is the fully-qualified name of the SessionService's
	// DeleteSession RPC.
	SessionServiceDeleteSessionProcedure = "/session.SessionService/DeleteSession"
	// SessionServiceGetSessionProcedure is the fully-qualified name of the SessionService's GetSession
	// RPC.
	SessionServiceGetSessionProcedure = "/session.SessionService/GetSession"
	// SessionServiceListSessionsProcedure is the fully-qualified name of the SessionService's
	// ListSessions RPC.
	SessionServiceListSessionsProcedure = "/session.SessionService/ListSessions"
	// SessionServicePublishSessionProcedure is the fully-qualified name of the SessionService's
	// PublishSession RPC.
	SessionServicePublishSessionProcedure = "/session.SessionService/PublishSession"
	// SessionServiceStartSessionProcedure is the fully-qualified name of the SessionService's
	// StartSession RPC.
	SessionServiceStartSessionProcedure = "/session.SessionService/StartSession"
	// SessionServiceEndSessionProcedure is the fully-qualified name of the SessionService's EndSession
	// RPC.
	SessionServiceEndSessionProcedure = "/session.SessionService/EndSession"
	// SessionServiceCancelSessionProcedure is the fully-qualified name of the SessionService's
	// CancelSession RPC.
	SessionServiceCancelSessionProcedure = "/session.SessionService/CancelSession"
	// SessionServiceCreateParticipantProcedure is the fully-qualified name of the SessionService's
	// CreateParticipant RPC.
	SessionServiceCreateParticipantProcedure = "/session.SessionService/CreateParticipant"
	// SessionServiceJoinSessionProcedure is the fully-qualified name of the SessionService's
	// JoinSession RPC.
	SessionServiceJoinSessionProcedure = "/session.SessionService/JoinSession"
	// SessionServiceLeaveSessionProcedure is the fully-qualified name of the SessionService's
	// LeaveSession RPC.
	SessionServiceLeaveSessionProcedure = "/session.SessionService/LeaveSession"
	// SessionServiceUpdateParticipantStatusProcedure is the fully-qualified name of the
	// SessionService's UpdateParticipantStatus RPC.
	SessionServiceUpdateParticipantStatusProcedure = "/session.SessionService/UpdateParticipantStatus"
	// SessionServiceRemoveParticipantProcedure is the fully-qualified name of the SessionService's
	// RemoveParticipant RPC.
	SessionServiceRemoveParticipantProcedure = "/session.SessionService/RemoveParticipant"
	// SessionServiceListParticipantsProcedure is the fully-qualified name of the SessionService's
	// ListParticipants RPC.
	SessionServiceListParticipantsProcedure = "/session.SessionService/ListParticipants"
)

// SessionServiceClient is a client for the session.SessionService service.
type SessionServiceClient interface {
	// Session Management
	CreateSession(context.Context, *connect.Request[sessions.CreateSessionRequest]) (*connect.Response[sessions.CreateSessionResponse], error)
	UpdateSession(context.Context, *connect.Request[sessions.UpdateSessionRequest]) (*connect.Response[sessions.UpdateSessionResponse], error)
	DeleteSession(context.Context, *connect.Request[sessions.DeleteSessionRequest]) (*connect.Response[sessions.DeleteSessionResponse], error)
	GetSession(context.Context, *connect.Request[sessions.GetSessionRequest]) (*connect.Response[sessions.GetSessionResponse], error)
	ListSessions(context.Context, *connect.Request[sessions.ListSessionsRequest]) (*connect.Response[sessions.ListSessionsResponse], error)
	// Session Lifecycle
	PublishSession(context.Context, *connect.Request[sessions.PublishSessionRequest]) (*connect.Response[sessions.PublishSessionResponse], error)
	StartSession(context.Context, *connect.Request[sessions.StartSessionRequest]) (*connect.Response[sessions.StartSessionResponse], error)
	EndSession(context.Context, *connect.Request[sessions.EndSessionRequest]) (*connect.Response[sessions.EndSessionResponse], error)
	CancelSession(context.Context, *connect.Request[sessions.CancelSessionRequest]) (*connect.Response[sessions.CancelSessionResponse], error)
	// Participant
	CreateParticipant(context.Context, *connect.Request[sessions.CreateParticipantRequest]) (*connect.Response[sessions.CreateParticipantResponse], error)
	JoinSession(context.Context, *connect.Request[sessions.JoinSessionRequest]) (*connect.Response[sessions.JoinSessionResponse], error)
	LeaveSession(context.Context, *connect.Request[sessions.LeaveSessionRequest]) (*connect.Response[sessions.LeaveSessionResponse], error)
	// Updates the status and properties of a session participant.
	// وضعیت و مشخصات شرکت‌کننده جلسه را به‌روزرسانی می‌کند.
	UpdateParticipantStatus(context.Context, *connect.Request[sessions.UpdateParticipantStatusRequest]) (*connect.Response[sessions.UpdateParticipantStatusResponse], error)
	RemoveParticipant(context.Context, *connect.Request[sessions.RemoveParticipantRequest]) (*connect.Response[sessions.RemoveParticipantResponse], error)
	ListParticipants(context.Context, *connect.Request[sessions.ListParticipantsRequest]) (*connect.Response[sessions.ListParticipantsResponse], error)
}

// NewSessionServiceClient constructs a client for the session.SessionService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSessionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SessionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sessionServiceMethods := sessions.File_sessions_session_proto.Services().ByName("SessionService").Methods()
	return &sessionServiceClient{
		createSession: connect.NewClient[sessions.CreateSessionRequest, sessions.CreateSessionResponse](
			httpClient,
			baseURL+SessionServiceCreateSessionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("CreateSession")),
			connect.WithClientOptions(opts...),
		),
		updateSession: connect.NewClient[sessions.UpdateSessionRequest, sessions.UpdateSessionResponse](
			httpClient,
			baseURL+SessionServiceUpdateSessionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("UpdateSession")),
			connect.WithClientOptions(opts...),
		),
		deleteSession: connect.NewClient[sessions.DeleteSessionRequest, sessions.DeleteSessionResponse](
			httpClient,
			baseURL+SessionServiceDeleteSessionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("DeleteSession")),
			connect.WithClientOptions(opts...),
		),
		getSession: connect.NewClient[sessions.GetSessionRequest, sessions.GetSessionResponse](
			httpClient,
			baseURL+SessionServiceGetSessionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("GetSession")),
			connect.WithClientOptions(opts...),
		),
		listSessions: connect.NewClient[sessions.ListSessionsRequest, sessions.ListSessionsResponse](
			httpClient,
			baseURL+SessionServiceListSessionsProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("ListSessions")),
			connect.WithClientOptions(opts...),
		),
		publishSession: connect.NewClient[sessions.PublishSessionRequest, sessions.PublishSessionResponse](
			httpClient,
			baseURL+SessionServicePublishSessionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("PublishSession")),
			connect.WithClientOptions(opts...),
		),
		startSession: connect.NewClient[sessions.StartSessionRequest, sessions.StartSessionResponse](
			httpClient,
			baseURL+SessionServiceStartSessionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("StartSession")),
			connect.WithClientOptions(opts...),
		),
		endSession: connect.NewClient[sessions.EndSessionRequest, sessions.EndSessionResponse](
			httpClient,
			baseURL+SessionServiceEndSessionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("EndSession")),
			connect.WithClientOptions(opts...),
		),
		cancelSession: connect.NewClient[sessions.CancelSessionRequest, sessions.CancelSessionResponse](
			httpClient,
			baseURL+SessionServiceCancelSessionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("CancelSession")),
			connect.WithClientOptions(opts...),
		),
		createParticipant: connect.NewClient[sessions.CreateParticipantRequest, sessions.CreateParticipantResponse](
			httpClient,
			baseURL+SessionServiceCreateParticipantProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("CreateParticipant")),
			connect.WithClientOptions(opts...),
		),
		joinSession: connect.NewClient[sessions.JoinSessionRequest, sessions.JoinSessionResponse](
			httpClient,
			baseURL+SessionServiceJoinSessionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("JoinSession")),
			connect.WithClientOptions(opts...),
		),
		leaveSession: connect.NewClient[sessions.LeaveSessionRequest, sessions.LeaveSessionResponse](
			httpClient,
			baseURL+SessionServiceLeaveSessionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("LeaveSession")),
			connect.WithClientOptions(opts...),
		),
		updateParticipantStatus: connect.NewClient[sessions.UpdateParticipantStatusRequest, sessions.UpdateParticipantStatusResponse](
			httpClient,
			baseURL+SessionServiceUpdateParticipantStatusProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("UpdateParticipantStatus")),
			connect.WithClientOptions(opts...),
		),
		removeParticipant: connect.NewClient[sessions.RemoveParticipantRequest, sessions.RemoveParticipantResponse](
			httpClient,
			baseURL+SessionServiceRemoveParticipantProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("RemoveParticipant")),
			connect.WithClientOptions(opts...),
		),
		listParticipants: connect.NewClient[sessions.ListParticipantsRequest, sessions.ListParticipantsResponse](
			httpClient,
			baseURL+SessionServiceListParticipantsProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("ListParticipants")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sessionServiceClient implements SessionServiceClient.
type sessionServiceClient struct {
	createSession           *connect.Client[sessions.CreateSessionRequest, sessions.CreateSessionResponse]
	updateSession           *connect.Client[sessions.UpdateSessionRequest, sessions.UpdateSessionResponse]
	deleteSession           *connect.Client[sessions.DeleteSessionRequest, sessions.DeleteSessionResponse]
	getSession              *connect.Client[sessions.GetSessionRequest, sessions.GetSessionResponse]
	listSessions            *connect.Client[sessions.ListSessionsRequest, sessions.ListSessionsResponse]
	publishSession          *connect.Client[sessions.PublishSessionRequest, sessions.PublishSessionResponse]
	startSession            *connect.Client[sessions.StartSessionRequest, sessions.StartSessionResponse]
	endSession              *connect.Client[sessions.EndSessionRequest, sessions.EndSessionResponse]
	cancelSession           *connect.Client[sessions.CancelSessionRequest, sessions.CancelSessionResponse]
	createParticipant       *connect.Client[sessions.CreateParticipantRequest, sessions.CreateParticipantResponse]
	joinSession             *connect.Client[sessions.JoinSessionRequest, sessions.JoinSessionResponse]
	leaveSession            *connect.Client[sessions.LeaveSessionRequest, sessions.LeaveSessionResponse]
	updateParticipantStatus *connect.Client[sessions.UpdateParticipantStatusRequest, sessions.UpdateParticipantStatusResponse]
	removeParticipant       *connect.Client[sessions.RemoveParticipantRequest, sessions.RemoveParticipantResponse]
	listParticipants        *connect.Client[sessions.ListParticipantsRequest, sessions.ListParticipantsResponse]
}

// CreateSession calls session.SessionService.CreateSession.
func (c *sessionServiceClient) CreateSession(ctx context.Context, req *connect.Request[sessions.CreateSessionRequest]) (*connect.Response[sessions.CreateSessionResponse], error) {
	return c.createSession.CallUnary(ctx, req)
}

// UpdateSession calls session.SessionService.UpdateSession.
func (c *sessionServiceClient) UpdateSession(ctx context.Context, req *connect.Request[sessions.UpdateSessionRequest]) (*connect.Response[sessions.UpdateSessionResponse], error) {
	return c.updateSession.CallUnary(ctx, req)
}

// DeleteSession calls session.SessionService.DeleteSession.
func (c *sessionServiceClient) DeleteSession(ctx context.Context, req *connect.Request[sessions.DeleteSessionRequest]) (*connect.Response[sessions.DeleteSessionResponse], error) {
	return c.deleteSession.CallUnary(ctx, req)
}

// GetSession calls session.SessionService.GetSession.
func (c *sessionServiceClient) GetSession(ctx context.Context, req *connect.Request[sessions.GetSessionRequest]) (*connect.Response[sessions.GetSessionResponse], error) {
	return c.getSession.CallUnary(ctx, req)
}

// ListSessions calls session.SessionService.ListSessions.
func (c *sessionServiceClient) ListSessions(ctx context.Context, req *connect.Request[sessions.ListSessionsRequest]) (*connect.Response[sessions.ListSessionsResponse], error) {
	return c.listSessions.CallUnary(ctx, req)
}

// PublishSession calls session.SessionService.PublishSession.
func (c *sessionServiceClient) PublishSession(ctx context.Context, req *connect.Request[sessions.PublishSessionRequest]) (*connect.Response[sessions.PublishSessionResponse], error) {
	return c.publishSession.CallUnary(ctx, req)
}

// StartSession calls session.SessionService.StartSession.
func (c *sessionServiceClient) StartSession(ctx context.Context, req *connect.Request[sessions.StartSessionRequest]) (*connect.Response[sessions.StartSessionResponse], error) {
	return c.startSession.CallUnary(ctx, req)
}

// EndSession calls session.SessionService.EndSession.
func (c *sessionServiceClient) EndSession(ctx context.Context, req *connect.Request[sessions.EndSessionRequest]) (*connect.Response[sessions.EndSessionResponse], error) {
	return c.endSession.CallUnary(ctx, req)
}

// CancelSession calls session.SessionService.CancelSession.
func (c *sessionServiceClient) CancelSession(ctx context.Context, req *connect.Request[sessions.CancelSessionRequest]) (*connect.Response[sessions.CancelSessionResponse], error) {
	return c.cancelSession.CallUnary(ctx, req)
}

// CreateParticipant calls session.SessionService.CreateParticipant.
func (c *sessionServiceClient) CreateParticipant(ctx context.Context, req *connect.Request[sessions.CreateParticipantRequest]) (*connect.Response[sessions.CreateParticipantResponse], error) {
	return c.createParticipant.CallUnary(ctx, req)
}

// JoinSession calls session.SessionService.JoinSession.
func (c *sessionServiceClient) JoinSession(ctx context.Context, req *connect.Request[sessions.JoinSessionRequest]) (*connect.Response[sessions.JoinSessionResponse], error) {
	return c.joinSession.CallUnary(ctx, req)
}

// LeaveSession calls session.SessionService.LeaveSession.
func (c *sessionServiceClient) LeaveSession(ctx context.Context, req *connect.Request[sessions.LeaveSessionRequest]) (*connect.Response[sessions.LeaveSessionResponse], error) {
	return c.leaveSession.CallUnary(ctx, req)
}

// UpdateParticipantStatus calls session.SessionService.UpdateParticipantStatus.
func (c *sessionServiceClient) UpdateParticipantStatus(ctx context.Context, req *connect.Request[sessions.UpdateParticipantStatusRequest]) (*connect.Response[sessions.UpdateParticipantStatusResponse], error) {
	return c.updateParticipantStatus.CallUnary(ctx, req)
}

// RemoveParticipant calls session.SessionService.RemoveParticipant.
func (c *sessionServiceClient) RemoveParticipant(ctx context.Context, req *connect.Request[sessions.RemoveParticipantRequest]) (*connect.Response[sessions.RemoveParticipantResponse], error) {
	return c.removeParticipant.CallUnary(ctx, req)
}

// ListParticipants calls session.SessionService.ListParticipants.
func (c *sessionServiceClient) ListParticipants(ctx context.Context, req *connect.Request[sessions.ListParticipantsRequest]) (*connect.Response[sessions.ListParticipantsResponse], error) {
	return c.listParticipants.CallUnary(ctx, req)
}

// SessionServiceHandler is an implementation of the session.SessionService service.
type SessionServiceHandler interface {
	// Session Management
	CreateSession(context.Context, *connect.Request[sessions.CreateSessionRequest]) (*connect.Response[sessions.CreateSessionResponse], error)
	UpdateSession(context.Context, *connect.Request[sessions.UpdateSessionRequest]) (*connect.Response[sessions.UpdateSessionResponse], error)
	DeleteSession(context.Context, *connect.Request[sessions.DeleteSessionRequest]) (*connect.Response[sessions.DeleteSessionResponse], error)
	GetSession(context.Context, *connect.Request[sessions.GetSessionRequest]) (*connect.Response[sessions.GetSessionResponse], error)
	ListSessions(context.Context, *connect.Request[sessions.ListSessionsRequest]) (*connect.Response[sessions.ListSessionsResponse], error)
	// Session Lifecycle
	PublishSession(context.Context, *connect.Request[sessions.PublishSessionRequest]) (*connect.Response[sessions.PublishSessionResponse], error)
	StartSession(context.Context, *connect.Request[sessions.StartSessionRequest]) (*connect.Response[sessions.StartSessionResponse], error)
	EndSession(context.Context, *connect.Request[sessions.EndSessionRequest]) (*connect.Response[sessions.EndSessionResponse], error)
	CancelSession(context.Context, *connect.Request[sessions.CancelSessionRequest]) (*connect.Response[sessions.CancelSessionResponse], error)
	// Participant
	CreateParticipant(context.Context, *connect.Request[sessions.CreateParticipantRequest]) (*connect.Response[sessions.CreateParticipantResponse], error)
	JoinSession(context.Context, *connect.Request[sessions.JoinSessionRequest]) (*connect.Response[sessions.JoinSessionResponse], error)
	LeaveSession(context.Context, *connect.Request[sessions.LeaveSessionRequest]) (*connect.Response[sessions.LeaveSessionResponse], error)
	// Updates the status and properties of a session participant.
	// وضعیت و مشخصات شرکت‌کننده جلسه را به‌روزرسانی می‌کند.
	UpdateParticipantStatus(context.Context, *connect.Request[sessions.UpdateParticipantStatusRequest]) (*connect.Response[sessions.UpdateParticipantStatusResponse], error)
	RemoveParticipant(context.Context, *connect.Request[sessions.RemoveParticipantRequest]) (*connect.Response[sessions.RemoveParticipantResponse], error)
	ListParticipants(context.Context, *connect.Request[sessions.ListParticipantsRequest]) (*connect.Response[sessions.ListParticipantsResponse], error)
}

// NewSessionServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSessionServiceHandler(svc SessionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sessionServiceMethods := sessions.File_sessions_session_proto.Services().ByName("SessionService").Methods()
	sessionServiceCreateSessionHandler := connect.NewUnaryHandler(
		SessionServiceCreateSessionProcedure,
		svc.CreateSession,
		connect.WithSchema(sessionServiceMethods.ByName("CreateSession")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceUpdateSessionHandler := connect.NewUnaryHandler(
		SessionServiceUpdateSessionProcedure,
		svc.UpdateSession,
		connect.WithSchema(sessionServiceMethods.ByName("UpdateSession")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceDeleteSessionHandler := connect.NewUnaryHandler(
		SessionServiceDeleteSessionProcedure,
		svc.DeleteSession,
		connect.WithSchema(sessionServiceMethods.ByName("DeleteSession")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceGetSessionHandler := connect.NewUnaryHandler(
		SessionServiceGetSessionProcedure,
		svc.GetSession,
		connect.WithSchema(sessionServiceMethods.ByName("GetSession")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceListSessionsHandler := connect.NewUnaryHandler(
		SessionServiceListSessionsProcedure,
		svc.ListSessions,
		connect.WithSchema(sessionServiceMethods.ByName("ListSessions")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServicePublishSessionHandler := connect.NewUnaryHandler(
		SessionServicePublishSessionProcedure,
		svc.PublishSession,
		connect.WithSchema(sessionServiceMethods.ByName("PublishSession")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceStartSessionHandler := connect.NewUnaryHandler(
		SessionServiceStartSessionProcedure,
		svc.StartSession,
		connect.WithSchema(sessionServiceMethods.ByName("StartSession")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceEndSessionHandler := connect.NewUnaryHandler(
		SessionServiceEndSessionProcedure,
		svc.EndSession,
		connect.WithSchema(sessionServiceMethods.ByName("EndSession")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceCancelSessionHandler := connect.NewUnaryHandler(
		SessionServiceCancelSessionProcedure,
		svc.CancelSession,
		connect.WithSchema(sessionServiceMethods.ByName("CancelSession")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceCreateParticipantHandler := connect.NewUnaryHandler(
		SessionServiceCreateParticipantProcedure,
		svc.CreateParticipant,
		connect.WithSchema(sessionServiceMethods.ByName("CreateParticipant")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceJoinSessionHandler := connect.NewUnaryHandler(
		SessionServiceJoinSessionProcedure,
		svc.JoinSession,
		connect.WithSchema(sessionServiceMethods.ByName("JoinSession")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceLeaveSessionHandler := connect.NewUnaryHandler(
		SessionServiceLeaveSessionProcedure,
		svc.LeaveSession,
		connect.WithSchema(sessionServiceMethods.ByName("LeaveSession")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceUpdateParticipantStatusHandler := connect.NewUnaryHandler(
		SessionServiceUpdateParticipantStatusProcedure,
		svc.UpdateParticipantStatus,
		connect.WithSchema(sessionServiceMethods.ByName("UpdateParticipantStatus")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceRemoveParticipantHandler := connect.NewUnaryHandler(
		SessionServiceRemoveParticipantProcedure,
		svc.RemoveParticipant,
		connect.WithSchema(sessionServiceMethods.ByName("RemoveParticipant")),
		connect.WithHandlerOptions(opts...),
	)
	sessionServiceListParticipantsHandler := connect.NewUnaryHandler(
		SessionServiceListParticipantsProcedure,
		svc.ListParticipants,
		connect.WithSchema(sessionServiceMethods.ByName("ListParticipants")),
		connect.WithHandlerOptions(opts...),
	)
	return "/session.SessionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SessionServiceCreateSessionProcedure:
			sessionServiceCreateSessionHandler.ServeHTTP(w, r)
		case SessionServiceUpdateSessionProcedure:
			sessionServiceUpdateSessionHandler.ServeHTTP(w, r)
		case SessionServiceDeleteSessionProcedure:
			sessionServiceDeleteSessionHandler.ServeHTTP(w, r)
		case SessionServiceGetSessionProcedure:
			sessionServiceGetSessionHandler.ServeHTTP(w, r)
		case SessionServiceListSessionsProcedure:
			sessionServiceListSessionsHandler.ServeHTTP(w, r)
		case SessionServicePublishSessionProcedure:
			sessionServicePublishSessionHandler.ServeHTTP(w, r)
		case SessionServiceStartSessionProcedure:
			sessionServiceStartSessionHandler.ServeHTTP(w, r)
		case SessionServiceEndSessionProcedure:
			sessionServiceEndSessionHandler.ServeHTTP(w, r)
		case SessionServiceCancelSessionProcedure:
			sessionServiceCancelSessionHandler.ServeHTTP(w, r)
		case SessionServiceCreateParticipantProcedure:
			sessionServiceCreateParticipantHandler.ServeHTTP(w, r)
		case SessionServiceJoinSessionProcedure:
			sessionServiceJoinSessionHandler.ServeHTTP(w, r)
		case SessionServiceLeaveSessionProcedure:
			sessionServiceLeaveSessionHandler.ServeHTTP(w, r)
		case SessionServiceUpdateParticipantStatusProcedure:
			sessionServiceUpdateParticipantStatusHandler.ServeHTTP(w, r)
		case SessionServiceRemoveParticipantProcedure:
			sessionServiceRemoveParticipantHandler.ServeHTTP(w, r)
		case SessionServiceListParticipantsProcedure:
			sessionServiceListParticipantsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSessionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSessionServiceHandler struct{}

func (UnimplementedSessionServiceHandler) CreateSession(context.Context, *connect.Request[sessions.CreateSessionRequest]) (*connect.Response[sessions.CreateSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("session.SessionService.CreateSession is not implemented"))
}

func (UnimplementedSessionServiceHandler) UpdateSession(context.Context, *connect.Request[sessions.UpdateSessionRequest]) (*connect.Response[sessions.UpdateSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("session.SessionService.UpdateSession is not implemented"))
}

func (UnimplementedSessionServiceHandler) DeleteSession(context.Context, *connect.Request[sessions.DeleteSessionRequest]) (*connect.Response[sessions.DeleteSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("session.SessionService.DeleteSession is not implemented"))
}

func (UnimplementedSessionServiceHandler) GetSession(context.Context, *connect.Request[sessions.GetSessionRequest]) (*connect.Response[sessions.GetSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("session.SessionService.GetSession is not implemented"))
}

func (UnimplementedSessionServiceHandler) ListSessions(context.Context, *connect.Request[sessions.ListSessionsRequest]) (*connect.Response[sessions.ListSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("session.SessionService.ListSessions is not implemented"))
}

func (UnimplementedSessionServiceHandler) PublishSession(context.Context, *connect.Request[sessions.PublishSessionRequest]) (*connect.Response[sessions.PublishSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("session.SessionService.PublishSession is not implemented"))
}

func (UnimplementedSessionServiceHandler) StartSession(context.Context, *connect.Request[sessions.StartSessionRequest]) (*connect.Response[sessions.StartSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("session.SessionService.StartSession is not implemented"))
}

func (UnimplementedSessionServiceHandler) EndSession(context.Context, *connect.Request[sessions.EndSessionRequest]) (*connect.Response[sessions.EndSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("session.SessionService.EndSession is not implemented"))
}

func (UnimplementedSessionServiceHandler) CancelSession(context.Context, *connect.Request[sessions.CancelSessionRequest]) (*connect.Response[sessions.CancelSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("session.SessionService.CancelSession is not implemented"))
}

func (UnimplementedSessionServiceHandler) CreateParticipant(context.Context, *connect.Request[sessions.CreateParticipantRequest]) (*connect.Response[sessions.CreateParticipantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("session.SessionService.CreateParticipant is not implemented"))
}

func (UnimplementedSessionServiceHandler) JoinSession(context.Context, *connect.Request[sessions.JoinSessionRequest]) (*connect.Response[sessions.JoinSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("session.SessionService.JoinSession is not implemented"))
}

func (UnimplementedSessionServiceHandler) LeaveSession(context.Context, *connect.Request[sessions.LeaveSessionRequest]) (*connect.Response[sessions.LeaveSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("session.SessionService.LeaveSession is not implemented"))
}

func (UnimplementedSessionServiceHandler) UpdateParticipantStatus(context.Context, *connect.Request[sessions.UpdateParticipantStatusRequest]) (*connect.Response[sessions.UpdateParticipantStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("session.SessionService.UpdateParticipantStatus is not implemented"))
}

func (UnimplementedSessionServiceHandler) RemoveParticipant(context.Context, *connect.Request[sessions.RemoveParticipantRequest]) (*connect.Response[sessions.RemoveParticipantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("session.SessionService.RemoveParticipant is not implemented"))
}

func (UnimplementedSessionServiceHandler) ListParticipants(context.Context, *connect.Request[sessions.ListParticipantsRequest]) (*connect.Response[sessions.ListParticipantsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("session.SessionService.ListParticipants is not implemented"))
}
