name: "Protocol Buffer Go Stubs Generation"
on:
  push:
    tags:
      - v**

jobs:
  protoc:
    name: "Generate"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["users", "", ""]
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.0
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install Buf
        run: |
          curl -sSL https://github.com/bufbuild/buf/releases/latest/download/buf-$(uname -s)-$(uname -m).tar.gz | tar -xz --strip-components=1 -C /usr/local/bin buf
          chmod +x /usr/local/bin/buf

      - name: Generate Go Code from Protobuf
        run: |
          buf generate --template buf.gen.yaml --path path/to/proto/files/${{ matrix.service }}